
const category = { 
    cleaner: function(inputList) {
            return inputList
                .filter(item => !item.match(/^Category:[a-zA-Z]{2,3}$/i))
                .filter(item => !item.includes('-0'))
                .filter(item => !item.includes('-1'))
                .filter(item => !item.includes('-2'))
                .filter(item => !item.includes('-3'))
                .filter(item => !item.includes('-4'))
                .filter(item => !item.includes('-5'))
                .filter(item => !item.includes('-N'))
                .filter(item => !item.includes('Category:Babel'))
                .filter(item => !item.includes('Category:Bureaucrats of Lingua Libre'))
                .filter(item => !item.includes('Category:Speakers in '))
                .filter(item => !item.includes('Category:Speakers of the month'))
                .filter(item => !item.includes('Category:Wiki Audio Walk'))
                .filter(item => !item.includes('Category:Events'))
                .filter(item => !item.includes('Category:LiLiZip'))
                .filter(item => !item.includes('Category:Lingua Libre templates'))
                .filter(item => !item.includes('Category:Speakers by language'));
        },
    list : [
    "Category:Ain",
    "Category:Ain-1",
    "Category:Ain-2",
    "Category:Ami",
    "Category:Ami-1",
    "Category:Ami-N",
    "Category:Ar",
    "Category:Ar-0",
    "Category:Ar-1",
    "Category:Ar-2",
    "Category:Ar-3",
    "Category:Ar-4",
    "Category:Ar-N",
    "Category:Arn",
    "Category:Arn-1",
    "Category:Arq",
    "Category:Arq-N",
    "Category:As",
    "Category:As-2",
    "Category:Ast",
    "Category:Ast-4",
    "Category:Ay",
    "Category:Ay-1",
    "Category:Az",
    "Category:Az-0",
    "Category:Az-N",
    "Category:Babel - Users by language",
    "Category:Babel box templates",
    "Category:Ban",
    "Category:Ban-N",
    "Category:Bcl",
    "Category:Bcl-N",
    "Category:Be",
    "Category:Be-2",
    "Category:Be-N",
    "Category:Bg",
    "Category:Bg-N",
    "Category:Bik",
    "Category:Bik-4",
    "Category:Blk",
    "Category:Blk-0",
    "Category:Blk-2",
    "Category:Blk-N",
    "Category:Bn",
    "Category:Bn-0",
    "Category:Bn-1",
    "Category:Bn-5",
    "Category:Bn-N",
    "Category:Bo",
    "Category:Bo-1",
    "Category:Bom",
    "Category:Bom-1",
    "Category:Bpy",
    "Category:Bpy-1",
    "Category:Br",
    "Category:Br-0",
    "Category:Br-3",
    "Category:Bureaucrats of Lingua Libre",
    "Category:Bureaucrats of Lingua Libre/en",
    "Category:Bureaucrats of Lingua Libre/fr",
    "Category:Bureaucrats of Lingua Libre/mk",
    "Category:Ca",
    "Category:Ca-0",
    "Category:Ca-1",
    "Category:Ca-2",
    "Category:Ca-3",
    "Category:Ca-N",
    "Category:Cdo-0",
    "Category:Cjy-0",
    "Category:Cmn",
    "Category:Cmn-1",
    "Category:Cmn-3",
    "Category:Cmn-4",
    "Category:Cnh",
    "Category:Cnh-1",
    "Category:Co",
    "Category:Co-2",
    "Category:Co-N",
    "Category:Cs-0",
    "Category:Da",
    "Category:Da-2",
    "Category:De",
    "Category:De-0",
    "Category:De-1",
    "Category:De-2",
    "Category:De-3",
    "Category:De-4",
    "Category:De-5",
    "Category:De-N",
    "Category:Drafts",
    "Category:Dtp",
    "Category:Dtp-0",
    "Category:Dtp-N",
    "Category:El",
    "Category:El-0",
    "Category:El-1",
    "Category:El-N",
    "Category:En",
    "Category:En-0",
    "Category:En-1",
    "Category:En-2",
    "Category:En-3",
    "Category:En-4",
    "Category:En-5",
    "Category:En-N",
    "Category:Eo",
    "Category:Eo-0",
    "Category:Eo-1",
    "Category:Eo-2",
    "Category:Eo-3",
    "Category:Es",
    "Category:Es-0",
    "Category:Es-1",
    "Category:Es-2",
    "Category:Es-3",
    "Category:Es-4",
    "Category:Es-N",
    "Category:Eu",
    "Category:Eu-0",
    "Category:Eu-1",
    "Category:Eu-N",
    "Category:Event by countries",
    "Category:Events",
    "Category:Events by date",
    "Category:Events in 2020",
    "Category:Events in 2021",
    "Category:Events in France",
    "Category:Fa",
    "Category:Fa-0",
    "Category:Fa-1",
    "Category:Fa-5",
    "Category:Fa-N",
    "Category:Fi",
    "Category:Fi-0",
    "Category:Fi-1",
    "Category:Fr",
    "Category:Fr-0",
    "Category:Fr-1",
    "Category:Fr-2",
    "Category:Fr-3",
    "Category:Fr-4",
    "Category:Fr-5",
    "Category:Fr-N",
    "Category:French meeting minutes",
    "Category:French meetings",
    "Category:Frp",
    "Category:Frp-5",
    "Category:Fy",
    "Category:Fy-1",
    "Category:Gan-0",
    "Category:Gl",
    "Category:Gl-1",
    "Category:Grc",
    "Category:Grc-0",
    "Category:Grc-1",
    "Category:Gsw",
    "Category:Gsw-1",
    "Category:Gsw-N",
    "Category:Guc",
    "Category:Guc-N",
    "Category:Ha",
    "Category:Ha-4",
    "Category:Hak",
    "Category:Hak-1",
    "Category:Haw",
    "Category:Haw-1",
    "Category:He",
    "Category:He-1",
    "Category:He-5",
    "Category:He-N",
    "Category:Hi",
    "Category:Hi-0",
    "Category:Hi-1",
    "Category:Hi-2",
    "Category:Hi-N",
    "Category:Hidden categories",
    "Category:Hoc",
    "Category:Hoc-2",
    "Category:Hr",
    "Category:Hr-4",
    "Category:Hsn-0",
    "Category:Ht",
    "Category:Ht-2",
    "Category:Hu",
    "Category:Hu-1",
    "Category:Hu-N",
    "Category:Hy",
    "Category:Hy-N",
    "Category:Id",
    "Category:Id-N",
    "Category:Ig",
    "Category:Ig-N",
    "Category:It",
    "Category:It-0",
    "Category:It-1",
    "Category:It-2",
    "Category:It-3",
    "Category:It-4",
    "Category:It-N",
    "Category:Iu",
    "Category:Iu-1",
    "Category:Ja",
    "Category:Ja-0",
    "Category:Ja-1",
    "Category:Ja-2",
    "Category:Ja-3",
    "Category:Ja-4",
    "Category:Ja-5",
    "Category:Ja-N",
    "Category:Jab-0",
    "Category:Juk-0",
    "Category:Ka",
    "Category:Ka-1",
    "Category:Kaa",
    "Category:Kaa-N",
    "Category:Kab",
    "Category:Kab-1",
    "Category:Kab-4",
    "Category:Kac",
    "Category:Kac-1",
    "Category:Kaj",
    "Category:Kaj-1",
    "Category:Kcg",
    "Category:Kcg-4",
    "Category:Ken",
    "Category:Ken-N",
    "Category:Kg",
    "Category:Kg-5",
    "Category:Ki-0",
    "Category:Kk",
    "Category:Kk-4",
    "Category:Kl-0",
    "Category:Km",
    "Category:Km-1",
    "Category:Kn-0",
    "Category:Ko",
    "Category:Ko-0",
    "Category:Ko-1",
    "Category:Ko-2",
    "Category:Ko-N",
    "Category:Ksw",
    "Category:Ksw-2",
    "Category:Ktu",
    "Category:Ktu-5",
    "Category:La",
    "Category:La-1",
    "Category:Ldi",
    "Category:Ldi-5",
    "Category:Len",
    "Category:Len-3",
    "Category:LiLiZip",
    "Category:Lic-0",
    "Category:License template",
    "Category:Lingua Libre",
    "Category:Lingua Libre/Drafts",
    "Category:Lingua Libre:DataViz",
    "Category:Lingua Libre:DataViz/id",
    "Category:Lingua Libre:DataViz/kaa",
    "Category:Lingua Libre:Help",
    "Category:Lingua Libre:Help/br",
    "Category:Lingua Libre:Help/ca",
    "Category:Lingua Libre:Help/de",
    "Category:Lingua Libre:Help/en",
    "Category:Lingua Libre:Help/eo",
    "Category:Lingua Libre:Help/fr",
    "Category:Lingua Libre:Help/gl",
    "Category:Lingua Libre:Help/he",
    "Category:Lingua Libre:Help/hyw",
    "Category:Lingua Libre:Help/ia",
    "Category:Lingua Libre:Help/id",
    "Category:Lingua Libre:Help/ja",
    "Category:Lingua Libre:Help/ko",
    "Category:Lingua Libre:Help/mk",
    "Category:Lingua Libre:Help/ms",
    "Category:Lingua Libre:Help/nb",
    "Category:Lingua Libre:Help/oc",
    "Category:Lingua Libre:Help/pl",
    "Category:Lingua Libre:Help/ru",
    "Category:Lingua Libre:Help/scn",
    "Category:Lingua Libre:Help/sv",
    "Category:Lingua Libre:Help/ta",
    "Category:Lingua Libre:Help/th",
    "Category:Lingua Libre:Help/tr",
    "Category:Lingua Libre:Help/yue",
    "Category:Lingua Libre discussion",
    "Category:Lingua Libre history",
    "Category:Lingua Libre maintenance",
    "Category:Lingua Libre templates",
    "Category:List template",
    "Category:Lmo-0",
    "Category:Ln",
    "Category:Ln-5",
    "Category:Lo",
    "Category:Lo-2",
    "Category:Lt",
    "Category:Lt-1",
    "Category:Lt-4",
    "Category:Lua",
    "Category:Lua-N",
    "Category:Lv",
    "Category:Lv-1",
    "Category:Mdw",
    "Category:Mdw-3",
    "Category:Meeting minutes by language",
    "Category:Meetings by language",
    "Category:Mg",
    "Category:Mg-N",
    "Category:Min",
    "Category:Min-3",
    "Category:Min-N",
    "Category:Mk",
    "Category:Mk-N",
    "Category:Ml",
    "Category:Ml-1",
    "Category:Ml-N",
    "Category:Mni",
    "Category:Mni-N",
    "Category:Mns",
    "Category:Mns-1",
    "Category:Mnw",
    "Category:Mnw-N",
    "Category:Mr",
    "Category:Mr-N",
    "Category:Ms",
    "Category:Ms-0",
    "Category:Ms-1",
    "Category:Ms-4",
    "Category:Ms-N",
    "Category:My",
    "Category:My-2",
    "Category:My-3",
    "Category:Nah-0",
    "Category:Nan",
    "Category:Nan-2",
    "Category:Nb",
    "Category:Nb-2",
    "Category:Nb-N",
    "Category:Nds",
    "Category:Nds-2",
    "Category:Nl",
    "Category:Nl-0",
    "Category:Nl-1",
    "Category:Nl-N",
    "Category:Nn",
    "Category:Nn-2",
    "Category:Nn-4",
    "Category:No",
    "Category:No-1",
    "Category:No-2",
    "Category:No-3",
    "Category:No-N",
    "Category:Nua",
    "Category:Nua-2",
    "Category:Nv-0",
    "Category:Obr",
    "Category:Obr-5",
    "Category:Oc",
    "Category:Oc-0",
    "Category:Oc-1",
    "Category:Oc-2",
    "Category:Oc-5",
    "Category:Oc-N",
    "Category:Omx",
    "Category:Omx-5",
    "Category:Or",
    "Category:Or-N",
    "Category:Oty",
    "Category:Oty-1",
    "Category:Pa",
    "Category:Pa-N",
    "Category:Pages using deprecated source tags",
    "Category:Pages with broken file links",
    "Category:Pages with script errors",
    "Category:Pcc-0",
    "Category:Pcm",
    "Category:Pcm-N",
    "Category:Pi",
    "Category:Pi-N",
    "Category:Pl",
    "Category:Pl-1",
    "Category:Pl-N",
    "Category:Pt",
    "Category:Pt-0",
    "Category:Pt-1",
    "Category:Pt-2",
    "Category:Pt-3",
    "Category:Pt-4",
    "Category:Pt-5",
    "Category:Pt-BR",
    "Category:Pt-BR-4",
    "Category:Pt-BR-N",
    "Category:Pt-N",
    "Category:Pwo",
    "Category:Pwo-2",
    "Category:Pyx",
    "Category:Pyx-5",
    "Category:Qu",
    "Category:Qu-0",
    "Category:Qu-2",
    "Category:Raw",
    "Category:Raw-2",
    "Category:Ro",
    "Category:Ro-1",
    "Category:Ro-3",
    "Category:Ro-N",
    "Category:Ru",
    "Category:Ru-0",
    "Category:Ru-1",
    "Category:Ru-2",
    "Category:Ru-3",
    "Category:Ru-4",
    "Category:Ru-N",
    "Category:Sa",
    "Category:Sa-1",
    "Category:Sa-5",
    "Category:Sat",
    "Category:Sat-N",
    "Category:Scn",
    "Category:Scn-4",
    "Category:Sdc",
    "Category:Sdc-2",
    "Category:Se",
    "Category:Se-1",
    "Category:Shn",
    "Category:Shn-1",
    "Category:Simple",
    "Category:Simple-5",
    "Category:Sk",
    "Category:Sk-1",
    "Category:Speakers ability templates",
    "Category:Speakers by language",
    "Category:Speakers in aai",
    "Category:Speakers in aak",
    "Category:Speakers in aau",
    "Category:Speakers in aaz",
    "Category:Speakers in abt",
    "Category:Speakers in aby",
    "Category:Speakers in acd",
    "Category:Speakers in ace",
    "Category:Speakers in acf",
    "Category:Speakers in ach",
    "Category:Speakers in acn",
    "Category:Speakers in acr",
    "Category:Speakers in acu",
    "Category:Speakers in acy",
    "Category:Speakers in ade",
    "Category:Speakers in adh",
    "Category:Speakers in adj",
    "Category:Speakers in ae",
    "Category:Speakers in ae-Latn",
    "Category:Speakers in aey",
    "Category:Speakers in agd",
    "Category:Speakers in agg",
    "Category:Speakers in agm",
    "Category:Speakers in agn",
    "Category:Speakers in agr",
    "Category:Speakers in ahk",
    "Category:Speakers in aia",
    "Category:Speakers in akb",
    "Category:Speakers in ake",
    "Category:Speakers in akh",
    "Category:Speakers in akp",
    "Category:Speakers in alj",
    "Category:Speakers in alp",
    "Category:Speakers in alt",
    "Category:Speakers in alz",
    "Category:Speakers in am",
    "Category:Speakers in ame",
    "Category:Speakers in amf",
    "Category:Speakers in amh",
    "Category:Speakers in ami",
    "Category:Speakers in amk",
    "Category:Speakers in amm",
    "Category:Speakers in amn",
    "Category:Speakers in amp",
    "Category:Speakers in amr",
    "Category:Speakers in amu",
    "Category:Speakers in ann",
    "Category:Speakers in anv",
    "Category:Speakers in aoj",
    "Category:Speakers in aom",
    "Category:Speakers in aon",
    "Category:Speakers in aoz",
    "Category:Speakers in ape",
    "Category:Speakers in apr",
    "Category:Speakers in apz",
    "Category:Speakers in ara",
    "Category:Speakers in arl",
    "Category:Speakers in arm",
    "Category:Speakers in asg",
    "Category:Speakers in aso",
    "Category:Speakers in ata",
    "Category:Speakers in atb",
    "Category:Speakers in atg",
    "Category:Speakers in atq",
    "Category:Speakers in auy",
    "Category:Speakers in av",
    "Category:Speakers in ava",
    "Category:Speakers in ave",
    "Category:Speakers in avn",
    "Category:Speakers in avt",
    "Category:Speakers in avu",
    "Category:Speakers in awa",
    "Category:Speakers in awb",
    "Category:Speakers in ay",
    "Category:Speakers in aym",
    "Category:Speakers in ayo",
    "Category:Speakers in az",
    "Category:Speakers in aze",
    "Category:Speakers in azg",
    "Category:Speakers in azz",
    "Category:Speakers in ba",
    "Category:Speakers in bak",
    "Category:Speakers in bam",
    "Category:Speakers in ban",
    "Category:Speakers in bao",
    "Category:Speakers in bav",
    "Category:Speakers in bba",
    "Category:Speakers in bbb",
    "Category:Speakers in bbo",
    "Category:Speakers in bbr",
    "Category:Speakers in bch",
    "Category:Speakers in bcl",
    "Category:Speakers in bcw",
    "Category:Speakers in bdd",
    "Category:Speakers in be",
    "Category:Speakers in be-tarask",
    "Category:Speakers in bef",
    "Category:Speakers in bel",
    "Category:Speakers in ben",
    "Category:Speakers in bep",
    "Category:Speakers in bex",
    "Category:Speakers in bfd",
    "Category:Speakers in bfo",
    "Category:Speakers in bg",
    "Category:Speakers in bgr",
    "Category:Speakers in bgz",
    "Category:Speakers in bhl",
    "Category:Speakers in bhw",
    "Category:Speakers in bi",
    "Category:Speakers in bib",
    "Category:Speakers in big",
    "Category:Speakers in bik",
    "Category:Speakers in bim",
    "Category:Speakers in bis",
    "Category:Speakers in biv",
    "Category:Speakers in bjr",
    "Category:Speakers in bjv",
    "Category:Speakers in bkl",
    "Category:Speakers in bku",
    "Category:Speakers in bkv",
    "Category:Speakers in blh",
    "Category:Speakers in blt-Latn",
    "Category:Speakers in blz",
    "Category:Speakers in bm",
    "Category:Speakers in bmh",
    "Category:Speakers in bmq",
    "Category:Speakers in bmr",
    "Category:Speakers in bmu",
    "Category:Speakers in bmv",
    "Category:Speakers in bn",
    "Category:Speakers in bnj",
    "Category:Speakers in bnp",
    "Category:Speakers in bo",
    "Category:Speakers in boa",
    "Category:Speakers in bod",
    "Category:Speakers in boj",
    "Category:Speakers in bon",
    "Category:Speakers in bos",
    "Category:Speakers in bov",
    "Category:Speakers in box",
    "Category:Speakers in bpr",
    "Category:Speakers in bps",
    "Category:Speakers in bqc",
    "Category:Speakers in bqj",
    "Category:Speakers in bqp",
    "Category:Speakers in bre",
    "Category:Speakers in bru",
    "Category:Speakers in bs",
    "Category:Speakers in bsn",
    "Category:Speakers in bss",
    "Category:Speakers in btd",
    "Category:Speakers in bts",
    "Category:Speakers in btt",
    "Category:Speakers in btx",
    "Category:Speakers in bua",
    "Category:Speakers in bud",
    "Category:Speakers in buk",
    "Category:Speakers in bul",
    "Category:Speakers in bus",
    "Category:Speakers in bvc",
    "Category:Speakers in bvz",
    "Category:Speakers in bwq",
    "Category:Speakers in bwu",
    "Category:Speakers in byr",
    "Category:Speakers in byx",
    "Category:Speakers in bzh",
    "Category:Speakers in bzi",
    "Category:Speakers in bzj",
    "Category:Speakers in ca-valencia",
    "Category:Speakers in caa",
    "Category:Speakers in cab",
    "Category:Speakers in cac",
    "Category:Speakers in cak",
    "Category:Speakers in cap",
    "Category:Speakers in car",
    "Category:Speakers in cat",
    "Category:Speakers in cax",
    "Category:Speakers in cbc",
    "Category:Speakers in cbi",
    "Category:Speakers in cbl",
    "Category:Speakers in cbr",
    "Category:Speakers in cbs",
    "Category:Speakers in cbt",
    "Category:Speakers in cbv",
    "Category:Speakers in cce",
    "Category:Speakers in ccp",
    "Category:Speakers in cdf",
    "Category:Speakers in ce",
    "Category:Speakers in ceb",
    "Category:Speakers in ceg",
    "Category:Speakers in ces",
    "Category:Speakers in cfm",
    "Category:Speakers in cgc",
    "Category:Speakers in che",
    "Category:Speakers in chj",
    "Category:Speakers in chm",
    "Category:Speakers in chr",
    "Category:Speakers in chv",
    "Category:Speakers in chz",
    "Category:Speakers in cjo",
    "Category:Speakers in cjp",
    "Category:Speakers in cjv",
    "Category:Speakers in cko",
    "Category:Speakers in cle",
    "Category:Speakers in cme",
    "Category:Speakers in cmn",
    "Category:Speakers in cmr",
    "Category:Speakers in cnh",
    "Category:Speakers in cni",
    "Category:Speakers in cnk",
    "Category:Speakers in cnl",
    "Category:Speakers in cnt",
    "Category:Speakers in coe",
    "Category:Speakers in cof",
    "Category:Speakers in cok",
    "Category:Speakers in con",
    "Category:Speakers in cot",
    "Category:Speakers in crh",
    "Category:Speakers in cs",
    "Category:Speakers in csk",
    "Category:Speakers in cso",
    "Category:Speakers in ctd-Latn",
    "Category:Speakers in ctu",
    "Category:Speakers in cub",
    "Category:Speakers in cuc",
    "Category:Speakers in cui",
    "Category:Speakers in cuk",
    "Category:Speakers in cul",
    "Category:Speakers in cv",
    "Category:Speakers in cwe",
    "Category:Speakers in cwt",
    "Category:Speakers in cy",
    "Category:Speakers in cya",
    "Category:Speakers in cym",
    "Category:Speakers in czt",
    "Category:Speakers in da",
    "Category:Speakers in daa",
    "Category:Speakers in dad",
    "Category:Speakers in dah",
    "Category:Speakers in dan",
    "Category:Speakers in ddn",
    "Category:Speakers in de",
    "Category:Speakers in ded",
    "Category:Speakers in des",
    "Category:Speakers in deu",
    "Category:Speakers in dga",
    "Category:Speakers in dgi",
    "Category:Speakers in dgz",
    "Category:Speakers in din",
    "Category:Speakers in dip",
    "Category:Speakers in djk",
    "Category:Speakers in dln",
    "Category:Speakers in dnw",
    "Category:Speakers in dob",
    "Category:Speakers in dop",
    "Category:Speakers in dsh",
    "Category:Speakers in dtb",
    "Category:Speakers in dtp",
    "Category:Speakers in dts",
    "Category:Speakers in due",
    "Category:Speakers in dug",
    "Category:Speakers in duo",
    "Category:Speakers in dwr",
    "Category:Speakers in dww",
    "Category:Speakers in dyi",
    "Category:Speakers in dyo",
    "Category:Speakers in dyu",
    "Category:Speakers in dz",
    "Category:Speakers in dzo",
    "Category:Speakers in ee",
    "Category:Speakers in eka",
    "Category:Speakers in el",
    "Category:Speakers in el-Latn-u-sd-it75",
    "Category:Speakers in ell",
    "Category:Speakers in emi",
    "Category:Speakers in emp",
    "Category:Speakers in enb",
    "Category:Speakers in eng",
    "Category:Speakers in enq",
    "Category:Speakers in enx",
    "Category:Speakers in epo",
    "Category:Speakers in eri",
    "Category:Speakers in es",
    "Category:Speakers in ese",
    "Category:Speakers in est",
    "Category:Speakers in et",
    "Category:Speakers in eu",
    "Category:Speakers in eus",
    "Category:Speakers in ewe",
    "Category:Speakers in ewo",
    "Category:Speakers in eza",
    "Category:Speakers in fa",
    "Category:Speakers in fa-AF",
    "Category:Speakers in faa",
    "Category:Speakers in fai",
    "Category:Speakers in fal",
    "Category:Speakers in fao",
    "Category:Speakers in far",
    "Category:Speakers in fas",
    "Category:Speakers in fi",
    "Category:Speakers in fij",
    "Category:Speakers in fil",
    "Category:Speakers in fin",
    "Category:Speakers in fip",
    "Category:Speakers in fit",
    "Category:Speakers in fj",
    "Category:Speakers in fo",
    "Category:Speakers in fon",
    "Category:Speakers in for",
    "Category:Speakers in fr",
    "Category:Speakers in fra",
    "Category:Speakers in fue",
    "Category:Speakers in fuf",
    "Category:Speakers in fuq",
    "Category:Speakers in fuv",
    "Category:Speakers in ga",
    "Category:Speakers in gag",
    "Category:Speakers in gah",
    "Category:Speakers in gam",
    "Category:Speakers in gaw",
    "Category:Speakers in gbi",
    "Category:Speakers in gd",
    "Category:Speakers in gde",
    "Category:Speakers in gdn",
    "Category:Speakers in gdr",
    "Category:Speakers in gej",
    "Category:Speakers in geo",
    "Category:Speakers in gfk",
    "Category:Speakers in ghs",
    "Category:Speakers in gil",
    "Category:Speakers in gkn",
    "Category:Speakers in gla",
    "Category:Speakers in gle",
    "Category:Speakers in glg",
    "Category:Speakers in glv",
    "Category:Speakers in gmv-Latn",
    "Category:Speakers in gn",
    "Category:Speakers in gnd",
    "Category:Speakers in gng",
    "Category:Speakers in gnw",
    "Category:Speakers in gof",
    "Category:Speakers in gog",
    "Category:Speakers in gor",
    "Category:Speakers in gqr",
    "Category:Speakers in grb",
    "Category:Speakers in grn",
    "Category:Speakers in grt",
    "Category:Speakers in gsc",
    "Category:Speakers in gso",
    "Category:Speakers in gsw-u-sd-chag",
    "Category:Speakers in gsw-u-sd-chbe",
    "Category:Speakers in gsw-u-sd-chfr",
    "Category:Speakers in gu",
    "Category:Speakers in gub",
    "Category:Speakers in guc",
    "Category:Speakers in gud",
    "Category:Speakers in guh",
    "Category:Speakers in gui",
    "Category:Speakers in guj",
    "Category:Speakers in gum",
    "Category:Speakers in gun",
    "Category:Speakers in guo",
    "Category:Speakers in guq",
    "Category:Speakers in gur",
    "Category:Speakers in gux",
    "Category:Speakers in gv",
    "Category:Speakers in gvc",
    "Category:Speakers in gvf",
    "Category:Speakers in gvl",
    "Category:Speakers in gwr",
    "Category:Speakers in gym",
    "Category:Speakers in gyr",
    "Category:Speakers in ha",
    "Category:Speakers in hae",
    "Category:Speakers in hag",
    "Category:Speakers in hat",
    "Category:Speakers in hau",
    "Category:Speakers in haw",
    "Category:Speakers in hay",
    "Category:Speakers in heh",
    "Category:Speakers in hi",
    "Category:Speakers in hif",
    "Category:Speakers in hig",
    "Category:Speakers in hil",
    "Category:Speakers in hin",
    "Category:Speakers in hla",
    "Category:Speakers in hmo",
    "Category:Speakers in hne",
    "Category:Speakers in hnn",
    "Category:Speakers in hns",
    "Category:Speakers in ho",
    "Category:Speakers in hot",
    "Category:Speakers in hr",
    "Category:Speakers in hrv",
    "Category:Speakers in ht",
    "Category:Speakers in hto",
    "Category:Speakers in hu",
    "Category:Speakers in hub",
    "Category:Speakers in hui",
    "Category:Speakers in hun",
    "Category:Speakers in hus",
    "Category:Speakers in huu",
    "Category:Speakers in huv",
    "Category:Speakers in hvn",
    "Category:Speakers in hy",
    "Category:Speakers in hye",
    "Category:Speakers in ian",
    "Category:Speakers in iba",
    "Category:Speakers in ibo",
    "Category:Speakers in icr",
    "Category:Speakers in id",
    "Category:Speakers in ifa",
    "Category:Speakers in ifb",
    "Category:Speakers in ife",
    "Category:Speakers in ifk",
    "Category:Speakers in ifu",
    "Category:Speakers in ify",
    "Category:Speakers in ig",
    "Category:Speakers in ign",
    "Category:Speakers in ik",
    "Category:Speakers in iku",
    "Category:Speakers in ilo",
    "Category:Speakers in imo",
    "Category:Speakers in inb",
    "Category:Speakers in ind",
    "Category:Speakers in ino",
    "Category:Speakers in iou",
    "Category:Speakers in ipi",
    "Category:Speakers in ipk",
    "Category:Speakers in iri",
    "Category:Speakers in irk",
    "Category:Speakers in iry",
    "Category:Speakers in it",
    "Category:Speakers in ita",
    "Category:Speakers in itv",
    "Category:Speakers in iu",
    "Category:Speakers in iws",
    "Category:Speakers in izr",
    "Category:Speakers in izz",
    "Category:Speakers in ja",
    "Category:Speakers in jac",
    "Category:Speakers in jae",
    "Category:Speakers in jam",
    "Category:Speakers in jav",
    "Category:Speakers in jbu",
    "Category:Speakers in jic",
    "Category:Speakers in jiv",
    "Category:Speakers in jmc",
    "Category:Speakers in jpn",
    "Category:Speakers in jun",
    "Category:Speakers in jv",
    "Category:Speakers in jvn",
    "Category:Speakers in ka",
    "Category:Speakers in kaa",
    "Category:Speakers in kab",
    "Category:Speakers in kab-Arab",
    "Category:Speakers in kab-Tfng",
    "Category:Speakers in kac",
    "Category:Speakers in kan",
    "Category:Speakers in kao",
    "Category:Speakers in kaq",
    "Category:Speakers in kat",
    "Category:Speakers in kaz",
    "Category:Speakers in kbh",
    "Category:Speakers in kbm",
    "Category:Speakers in kbp",
    "Category:Speakers in kbq",
    "Category:Speakers in kbr",
    "Category:Speakers in kcg",
    "Category:Speakers in kdc",
    "Category:Speakers in kdi",
    "Category:Speakers in kdj",
    "Category:Speakers in kdn",
    "Category:Speakers in kek",
    "Category:Speakers in ken",
    "Category:Speakers in keo",
    "Category:Speakers in ker",
    "Category:Speakers in kew",
    "Category:Speakers in kez",
    "Category:Speakers in kgf",
    "Category:Speakers in kgr",
    "Category:Speakers in khm",
    "Category:Speakers in khz",
    "Category:Speakers in kia",
    "Category:Speakers in kij",
    "Category:Speakers in kin",
    "Category:Speakers in kir",
    "Category:Speakers in kj",
    "Category:Speakers in kjb",
    "Category:Speakers in kje",
    "Category:Speakers in kjh",
    "Category:Speakers in kjs",
    "Category:Speakers in kk",
    "Category:Speakers in kki",
    "Category:Speakers in kkj",
    "Category:Speakers in kln",
    "Category:Speakers in km",
    "Category:Speakers in kma",
    "Category:Speakers in kmg",
    "Category:Speakers in kmo",
    "Category:Speakers in kms",
    "Category:Speakers in kmu",
    "Category:Speakers in kn",
    "Category:Speakers in kne",
    "Category:Speakers in knf",
    "Category:Speakers in knj",
    "Category:Speakers in knk",
    "Category:Speakers in kno",
    "Category:Speakers in knv",
    "Category:Speakers in kog",
    "Category:Speakers in kom",
    "Category:Speakers in kpf",
    "Category:Speakers in kpg",
    "Category:Speakers in kpr",
    "Category:Speakers in kpw",
    "Category:Speakers in kpx",
    "Category:Speakers in kpz",
    "Category:Speakers in kqc",
    "Category:Speakers in kqe",
    "Category:Speakers in kqp",
    "Category:Speakers in kqw",
    "Category:Speakers in kqy",
    "Category:Speakers in krc",
    "Category:Speakers in kri",
    "Category:Speakers in krj",
    "Category:Speakers in kru",
    "Category:Speakers in ksd",
    "Category:Speakers in ksr",
    "Category:Speakers in ktb",
    "Category:Speakers in ktj",
    "Category:Speakers in kto",
    "Category:Speakers in ku",
    "Category:Speakers in kua",
    "Category:Speakers in kub",
    "Category:Speakers in kud",
    "Category:Speakers in kue",
    "Category:Speakers in kum",
    "Category:Speakers in kup",
    "Category:Speakers in kur",
    "Category:Speakers in kus",
    "Category:Speakers in kv",
    "Category:Speakers in kvn",
    "Category:Speakers in kwf",
    "Category:Speakers in kwi",
    "Category:Speakers in kwj",
    "Category:Speakers in kxc",
    "Category:Speakers in kxm",
    "Category:Speakers in ky",
    "Category:Speakers in kyc",
    "Category:Speakers in kyf",
    "Category:Speakers in kyg",
    "Category:Speakers in kyq",
    "Category:Speakers in kyu",
    "Category:Speakers in kyz",
    "Category:Speakers in kze",
    "Category:Speakers in kzf",
    "Category:Speakers in kzj",
    "Category:Speakers in laj",
    "Category:Speakers in lao",
    "Category:Speakers in las",
    "Category:Speakers in lat",
    "Category:Speakers in lav",
    "Category:Speakers in law",
    "Category:Speakers in lcm",
    "Category:Speakers in lee",
    "Category:Speakers in lef",
    "Category:Speakers in lem",
    "Category:Speakers in leu",
    "Category:Speakers in lew",
    "Category:Speakers in lex",
    "Category:Speakers in lgg",
    "Category:Speakers in lhu",
    "Category:Speakers in lia",
    "Category:Speakers in lid",
    "Category:Speakers in lif",
    "Category:Speakers in lip",
    "Category:Speakers in lis",
    "Category:Speakers in lit",
    "Category:Speakers in ljp",
    "Category:Speakers in lln",
    "Category:Speakers in lme",
    "Category:Speakers in lmk",
    "Category:Speakers in lnd",
    "Category:Speakers in lob",
    "Category:Speakers in loe",
    "Category:Speakers in lok",
    "Category:Speakers in lon",
    "Category:Speakers in lsi",
    "Category:Speakers in lsm",
    "Category:Speakers in ltz",
    "Category:Speakers in luc",
    "Category:Speakers in lus",
    "Category:Speakers in lwo",
    "Category:Speakers in maa",
    "Category:Speakers in mad",
    "Category:Speakers in mag",
    "Category:Speakers in mah",
    "Category:Speakers in mai",
    "Category:Speakers in maj",
    "Category:Speakers in mak",
    "Category:Speakers in mal",
    "Category:Speakers in mam",
    "Category:Speakers in mar",
    "Category:Speakers in maw",
    "Category:Speakers in maz",
    "Category:Speakers in mbb",
    "Category:Speakers in mbc",
    "Category:Speakers in mbh",
    "Category:Speakers in mbt",
    "Category:Speakers in mca",
    "Category:Speakers in mcb",
    "Category:Speakers in mcd",
    "Category:Speakers in mco",
    "Category:Speakers in mcp",
    "Category:Speakers in mcq",
    "Category:Speakers in mcu",
    "Category:Speakers in mda",
    "Category:Speakers in mdy",
    "Category:Speakers in med",
    "Category:Speakers in mee",
    "Category:Speakers in mej",
    "Category:Speakers in mek",
    "Category:Speakers in men",
    "Category:Speakers in meq",
    "Category:Speakers in meu",
    "Category:Speakers in mfe",
    "Category:Speakers in mfh",
    "Category:Speakers in mfi",
    "Category:Speakers in mfk",
    "Category:Speakers in mfq",
    "Category:Speakers in mfy",
    "Category:Speakers in mfz",
    "Category:Speakers in mgd",
    "Category:Speakers in mgh",
    "Category:Speakers in mgo",
    "Category:Speakers in mhi",
    "Category:Speakers in mhl",
    "Category:Speakers in mhx",
    "Category:Speakers in mhy",
    "Category:Speakers in mib",
    "Category:Speakers in mif",
    "Category:Speakers in mil",
    "Category:Speakers in min",
    "Category:Speakers in mio",
    "Category:Speakers in miq",
    "Category:Speakers in mit",
    "Category:Speakers in mkd",
    "Category:Speakers in mkl",
    "Category:Speakers in mlg",
    "Category:Speakers in mlh",
    "Category:Speakers in mlp",
    "Category:Speakers in mlt",
    "Category:Speakers in mmo",
    "Category:Speakers in mmx",
    "Category:Speakers in mna",
    "Category:Speakers in mnb",
    "Category:Speakers in mnf",
    "Category:Speakers in mnw",
    "Category:Speakers in moa",
    "Category:Speakers in mog",
    "Category:Speakers in mop",
    "Category:Speakers in mor",
    "Category:Speakers in mox",
    "Category:Speakers in mpg",
    "Category:Speakers in mpm",
    "Category:Speakers in mps",
    "Category:Speakers in mpt",
    "Category:Speakers in mpx",
    "Category:Speakers in mqb",
    "Category:Speakers in mqj",
    "Category:Speakers in mqn",
    "Category:Speakers in mr",
    "Category:Speakers in mri",
    "Category:Speakers in mrw",
    "Category:Speakers in msa",
    "Category:Speakers in msm",
    "Category:Speakers in msy",
    "Category:Speakers in mta",
    "Category:Speakers in mti",
    "Category:Speakers in mtj",
    "Category:Speakers in mto",
    "Category:Speakers in mtp",
    "Category:Speakers in muh",
    "Category:Speakers in mur",
    "Category:Speakers in mux",
    "Category:Speakers in muy",
    "Category:Speakers in mva",
    "Category:Speakers in mvp",
    "Category:Speakers in mwv",
    "Category:Speakers in mxb",
    "Category:Speakers in mxt",
    "Category:Speakers in mya",
    "Category:Speakers in myb",
    "Category:Speakers in myk",
    "Category:Speakers in myv",
    "Category:Speakers in myw",
    "Category:Speakers in myx",
    "Category:Speakers in myy",
    "Category:Speakers in mza",
    "Category:Speakers in mzi",
    "Category:Speakers in mzk",
    "Category:Speakers in mzm",
    "Category:Speakers in naf",
    "Category:Speakers in nak",
    "Category:Speakers in nas",
    "Category:Speakers in nca",
    "Category:Speakers in nch",
    "Category:Speakers in ncj",
    "Category:Speakers in ncu",
    "Category:Speakers in ndj",
    "Category:Speakers in ndy",
    "Category:Speakers in ndz",
    "Category:Speakers in neb",
    "Category:Speakers in new",
    "Category:Speakers in nfr",
    "Category:Speakers in ngp",
    "Category:Speakers in nho",
    "Category:Speakers in nhu",
    "Category:Speakers in nhw",
    "Category:Speakers in nhy",
    "Category:Speakers in nia",
    "Category:Speakers in nii",
    "Category:Speakers in nij",
    "Category:Speakers in nim",
    "Category:Speakers in nin",
    "Category:Speakers in nkf",
    "Category:Speakers in nko",
    "Category:Speakers in nlc",
    "Category:Speakers in nld",
    "Category:Speakers in nmz",
    "Category:Speakers in nnb",
    "Category:Speakers in nnq",
    "Category:Speakers in nnw",
    "Category:Speakers in noa",
    "Category:Speakers in nog",
    "Category:Speakers in nop",
    "Category:Speakers in not",
    "Category:Speakers in nou",
    "Category:Speakers in npl",
    "Category:Speakers in npy",
    "Category:Speakers in nsn",
    "Category:Speakers in nsu",
    "Category:Speakers in ntm",
    "Category:Speakers in ntp",
    "Category:Speakers in ntr",
    "Category:Speakers in nuj",
    "Category:Speakers in nus",
    "Category:Speakers in nvm",
    "Category:Speakers in nwb",
    "Category:Speakers in nwi",
    "Category:Speakers in nya",
    "Category:Speakers in nyf",
    "Category:Speakers in nyn",
    "Category:Speakers in nyo",
    "Category:Speakers in nyy",
    "Category:Speakers in nzi",
    "Category:Speakers in obo",
    "Category:Speakers in oci",
    "Category:Speakers in oku",
    "Category:Speakers in okv",
    "Category:Speakers in old",
    "Category:Speakers in ong",
    "Category:Speakers in opm",
    "Category:Speakers in ori",
    "Category:Speakers in osa",
    "Category:Speakers in oss",
    "Category:Speakers in otd",
    "Category:Speakers in ote",
    "Category:Speakers in ozm",
    "Category:Speakers in pab",
    "Category:Speakers in pad",
    "Category:Speakers in pag",
    "Category:Speakers in pah",
    "Category:Speakers in pam",
    "Category:Speakers in pan",
    "Category:Speakers in pau",
    "Category:Speakers in pbc",
    "Category:Speakers in pbi",
    "Category:Speakers in pck",
    "Category:Speakers in pcm",
    "Category:Speakers in pez",
    "Category:Speakers in pib",
    "Category:Speakers in pir",
    "Category:Speakers in pis",
    "Category:Speakers in pjt",
    "Category:Speakers in pkb",
    "Category:Speakers in plw",
    "Category:Speakers in pmf",
    "Category:Speakers in pny",
    "Category:Speakers in poh",
    "Category:Speakers in poi",
    "Category:Speakers in pol",
    "Category:Speakers in por",
    "Category:Speakers in poy",
    "Category:Speakers in ppk",
    "Category:Speakers in ppo",
    "Category:Speakers in prf",
    "Category:Speakers in prk",
    "Category:Speakers in pss",
    "Category:Speakers in pt-PT",
    "Category:Speakers in ptp",
    "Category:Speakers in ptu",
    "Category:Speakers in pus",
    "Category:Speakers in pwg",
    "Category:Speakers in pww",
    "Category:Speakers in pxm",
    "Category:Speakers in qub",
    "Category:Speakers in quc",
    "Category:Speakers in que",
    "Category:Speakers in quf",
    "Category:Speakers in quh",
    "Category:Speakers in qul",
    "Category:Speakers in qup",
    "Category:Speakers in quw",
    "Category:Speakers in quy",
    "Category:Speakers in qvc",
    "Category:Speakers in qve",
    "Category:Speakers in qvi",
    "Category:Speakers in qvm",
    "Category:Speakers in qvn",
    "Category:Speakers in qvo",
    "Category:Speakers in qvs",
    "Category:Speakers in qvw",
    "Category:Speakers in qvz",
    "Category:Speakers in qwh",
    "Category:Speakers in qxh",
    "Category:Speakers in qxl",
    "Category:Speakers in qxn",
    "Category:Speakers in qxo",
    "Category:Speakers in qxr",
    "Category:Speakers in rai",
    "Category:Speakers in raj",
    "Category:Speakers in rav",
    "Category:Speakers in rej",
    "Category:Speakers in rim",
    "Category:Speakers in rmc",
    "Category:Speakers in rmo",
    "Category:Speakers in rnl",
    "Category:Speakers in ro-MD",
    "Category:Speakers in roh-puter",
    "Category:Speakers in roh-rumgr",
    "Category:Speakers in roh-surmiran",
    "Category:Speakers in roh-sursilv",
    "Category:Speakers in roh-sutsilv",
    "Category:Speakers in roh-vallader",
    "Category:Speakers in rom",
    "Category:Speakers in ron",
    "Category:Speakers in roo",
    "Category:Speakers in rro",
    "Category:Speakers in ruf",
    "Category:Speakers in rug",
    "Category:Speakers in run",
    "Category:Speakers in rus",
    "Category:Speakers in rwo",
    "Category:Speakers in sab",
    "Category:Speakers in sag",
    "Category:Speakers in sah",
    "Category:Speakers in sas",
    "Category:Speakers in sat",
    "Category:Speakers in sba",
    "Category:Speakers in sbl",
    "Category:Speakers in sck",
    "Category:Speakers in scn",
    "Category:Speakers in sda",
    "Category:Speakers in seh",
    "Category:Speakers in sey",
    "Category:Speakers in sgb",
    "Category:Speakers in sgw",
    "Category:Speakers in sgz",
    "Category:Speakers in shk",
    "Category:Speakers in shn",
    "Category:Speakers in shp",
    "Category:Speakers in sig",
    "Category:Speakers in sil",
    "Category:Speakers in sim",
    "Category:Speakers in sin",
    "Category:Speakers in sja",
    "Category:Speakers in sld",
    "Category:Speakers in slk",
    "Category:Speakers in sll",
    "Category:Speakers in slv",
    "Category:Speakers in smo",
    "Category:Speakers in smt",
    "Category:Speakers in sna",
    "Category:Speakers in snc",
    "Category:Speakers in snn",
    "Category:Speakers in snp",
    "Category:Speakers in snw",
    "Category:Speakers in sny",
    "Category:Speakers in som",
    "Category:Speakers in soq",
    "Category:Speakers in soy",
    "Category:Speakers in spa",
    "Category:Speakers in spl",
    "Category:Speakers in spp",
    "Category:Speakers in sps",
    "Category:Speakers in sqi",
    "Category:Speakers in sr-Latn",
    "Category:Speakers in sri",
    "Category:Speakers in srm",
    "Category:Speakers in srn",
    "Category:Speakers in srp",
    "Category:Speakers in ssd",
    "Category:Speakers in ssg",
    "Category:Speakers in ssx",
    "Category:Speakers in stn",
    "Category:Speakers in sua",
    "Category:Speakers in sue",
    "Category:Speakers in sun",
    "Category:Speakers in sur",
    "Category:Speakers in sus",
    "Category:Speakers in suz",
    "Category:Speakers in sve",
    "Category:Speakers in swa",
    "Category:Speakers in swp",
    "Category:Speakers in sxn",
    "Category:Speakers in tab",
    "Category:Speakers in taj",
    "Category:Speakers in tam",
    "Category:Speakers in tap",
    "Category:Speakers in taq",
    "Category:Speakers in tat",
    "Category:Speakers in tav",
    "Category:Speakers in taw",
    "Category:Speakers in tbc",
    "Category:Speakers in tbg",
    "Category:Speakers in tbo",
    "Category:Speakers in tby",
    "Category:Speakers in tbz",
    "Category:Speakers in tca",
    "Category:Speakers in tcc",
    "Category:Speakers in ted",
    "Category:Speakers in tel",
    "Category:Speakers in tem",
    "Category:Speakers in teo",
    "Category:Speakers in ter",
    "Category:Speakers in tfr",
    "Category:Speakers in tgo",
    "Category:Speakers in tgp",
    "Category:Speakers in thk",
    "Category:Speakers in tif",
    "Category:Speakers in tih",
    "Category:Speakers in tik",
    "Category:Speakers in tim",
    "Category:Speakers in tir",
    "Category:Speakers in tlb",
    "Category:Speakers in tlf",
    "Category:Speakers in tlj",
    "Category:Speakers in tmc",
    "Category:Speakers in tna",
    "Category:Speakers in tnr",
    "Category:Speakers in tob",
    "Category:Speakers in toc",
    "Category:Speakers in toh",
    "Category:Speakers in tok",
    "Category:Speakers in ton",
    "Category:Speakers in top",
    "Category:Speakers in tos",
    "Category:Speakers in tpi",
    "Category:Speakers in tpm",
    "Category:Speakers in tpp",
    "Category:Speakers in tpt",
    "Category:Speakers in tpz",
    "Category:Speakers in tqo",
    "Category:Speakers in trs",
    "Category:Speakers in tsz",
    "Category:Speakers in ttc",
    "Category:Speakers in tte",
    "Category:Speakers in tue",
    "Category:Speakers in tuf",
    "Category:Speakers in tuk",
    "Category:Speakers in tur",
    "Category:Speakers in twb",
    "Category:Speakers in twu",
    "Category:Speakers in txa",
    "Category:Speakers in txu",
    "Category:Speakers in tyv",
    "Category:Speakers in tyz",
    "Category:Speakers in tzh",
    "Category:Speakers in tzj",
    "Category:Speakers in ubr",
    "Category:Speakers in ubu",
    "Category:Speakers in udm",
    "Category:Speakers in udu",
    "Category:Speakers in uig",
    "Category:Speakers in ukr",
    "Category:Speakers in ura",
    "Category:Speakers in urb",
    "Category:Speakers in urd",
    "Category:Speakers in urk",
    "Category:Speakers in ury",
    "Category:Speakers in usa",
    "Category:Speakers in usp",
    "Category:Speakers in uvl",
    "Category:Speakers in uzb",
    "Category:Speakers in vag",
    "Category:Speakers in vec",
    "Category:Speakers in vec-u-sd-itpd",
    "Category:Speakers in vec-u-sd-itts",
    "Category:Speakers in vec-u-sd-itvr",
    "Category:Speakers in vid",
    "Category:Speakers in vie",
    "Category:Speakers in viv",
    "Category:Speakers in vmw",
    "Category:Speakers in vun",
    "Category:Speakers in vut",
    "Category:Speakers in waj",
    "Category:Speakers in wap",
    "Category:Speakers in war",
    "Category:Speakers in way",
    "Category:Speakers in wer",
    "Category:Speakers in wiu",
    "Category:Speakers in wlx",
    "Category:Speakers in wmw",
    "Category:Speakers in wnc",
    "Category:Speakers in wnu",
    "Category:Speakers in wob",
    "Category:Speakers in wos",
    "Category:Speakers in wrs",
    "Category:Speakers in wsk",
    "Category:Speakers in wuv",
    "Category:Speakers in wwa",
    "Category:Speakers in xal",
    "Category:Speakers in xav",
    "Category:Speakers in xed",
    "Category:Speakers in xla",
    "Category:Speakers in xog",
    "Category:Speakers in xrb",
    "Category:Speakers in xsb",
    "Category:Speakers in xsi",
    "Category:Speakers in xsm",
    "Category:Speakers in xsr",
    "Category:Speakers in xsu",
    "Category:Speakers in xtd",
    "Category:Speakers in xtm",
    "Category:Speakers in xuo",
    "Category:Speakers in yaa",
    "Category:Speakers in yad",
    "Category:Speakers in yal",
    "Category:Speakers in yam",
    "Category:Speakers in yaz",
    "Category:Speakers in yby",
    "Category:Speakers in ycn",
    "Category:Speakers in yle",
    "Category:Speakers in yli",
    "Category:Speakers in yml",
    "Category:Speakers in yon",
    "Category:Speakers in yor",
    "Category:Speakers in yrb",
    "Category:Speakers in yre",
    "Category:Speakers in yss",
    "Category:Speakers in yua",
    "Category:Speakers in yue",
    "Category:Speakers in yuj",
    "Category:Speakers in yut",
    "Category:Speakers in yuw",
    "Category:Speakers in yva",
    "Category:Speakers in zaa",
    "Category:Speakers in zad",
    "Category:Speakers in zae",
    "Category:Speakers in zap",
    "Category:Speakers in zas",
    "Category:Speakers in zaw",
    "Category:Speakers in zca",
    "Category:Speakers in zia",
    "Category:Speakers in ziw",
    "Category:Speakers in zlm",
    "Category:Speakers in zne",
    "Category:Speakers in zpc",
    "Category:Speakers in zpi",
    "Category:Speakers in zpq",
    "Category:Speakers in zpt",
    "Category:Speakers in zpz",
    "Category:Speakers in zyp",
    "Category:Speakers of the month",
    "Category:Sr",
    "Category:Sr-4",
    "Category:Su",
    "Category:Su-1",
    "Category:Sv",
    "Category:Sv-0",
    "Category:Sv-1",
    "Category:Sv-2",
    "Category:Sv-3",
    "Category:Sv-N",
    "Category:Sw",
    "Category:Sw-2",
    "Category:Sxu",
    "Category:Sxu-3",
    "Category:Syc-0",
    "Category:Ta",
    "Category:Ta-N",
    "Category:Te",
    "Category:Te-N",
    "Category:Technical reports",
    "Category:Tg",
    "Category:Tg-4",
    "Category:Th",
    "Category:Th-2",
    "Category:Tk",
    "Category:Tk-N",
    "Category:Tl",
    "Category:Tl-5",
    "Category:Tlh",
    "Category:Tlh-1",
    "Category:Tly",
    "Category:Tly-N",
    "Category:Tool",
    "Category:Toy",
    "Category:Toy-N",
    "Category:Tpw",
    "Category:Tpw-1",
    "Category:Tpw-2",
    "Category:Tr",
    "Category:Tr-1",
    "Category:Tr-5",
    "Category:Tr-N",
    "Category:Tvd-0",
    "Category:Tvn",
    "Category:Tvn-2",
    "Category:Ubl",
    "Category:Ubl-1",
    "Category:Udm",
    "Category:Udm-1",
    "Category:Uk",
    "Category:Uk-0",
    "Category:Uk-1",
    "Category:Uk-2",
    "Category:Uk-N",
    "Category:User groups",
    "Category:User message templates",
    "Category:Uz",
    "Category:Uz-1",
    "Category:Uz-5",
    "Category:Vi-0",
    "Category:Wae",
    "Category:Wae-2",
    "Category:Wae-3",
    "Category:Wiki Audio Walk",
    "Category:Wiki Audio Walk 2025",
    "Category:Wiki Audio Walk 2025/Kcg",
    "Category:Wuu-0",
    "Category:Yi",
    "Category:Yi-1",
    "Category:Yo",
    "Category:Yo-1",
    "Category:Yue",
    "Category:Yue-4",
    "Category:Yue-N",
    "Category:Za-0",
    "Category:Zh",
    "Category:Zh-0",
    "Category:Zh-1",
    "Category:Zh-2",
    "Category:Zh-3",
    "Category:Zh-N",
    "Category:Zlm",
    "Category:Zlm-4",
    "Category:Zmi",
    "Category:Zmi-4",
    "Category:Zsm",
    "Category:Zsm-4",
    "Category:Zsm-N"
]
};
// Export to global scope for browser access
if (typeof window !== 'undefined') {
    window.category = category;
}
