const help = { 
    cleaner: function(inputList) {
            return inputList
                //.filter(item => !item.includes('Template:Autopatrolled'))
                .filter(item => !item.includes('Help:Add a new language'))
                .filter(item => !item.includes('Help:Documentation opérationelle'))
                .filter(item => !item.includes('Help:Rename'))
                .filter(item => !item.includes('Help:SPARQL'))
                .filter(item => !/\/([a-z]{2,3}(-[a-z]{2,4})?)$/.test(item));
        },
    list : [
    "Help:API",
    "Help:APIs",
    "Help:Add a new language",
    "Help:Add a new language/bn",
    "Help:Add a new language/br",
    "Help:Add a new language/de",
    "Help:Add a new language/en",
    "Help:Add a new language/eo",
    "Help:Add a new language/es",
    "Help:Add a new language/fr",
    "Help:Add a new language/he",
    "Help:Add a new language/hyw",
    "Help:Add a new language/ia",
    "Help:Add a new language/id",
    "Help:Add a new language/ja",
    "Help:Add a new language/mk",
    "Help:Add a new language/mni",
    "Help:Add a new language/nb",
    "Help:Add a new language/oc",
    "Help:Add a new language/pl",
    "Help:Add a new language/pt-br",
    "Help:Add a new language/ro",
    "Help:Add a new language/ru",
    "Help:Add a new language/scn",
    "Help:Add a new language/sv",
    "Help:Add a new language/th",
    "Help:Add a new language/tr",
    "Help:Add a new language/zh-tw",
    "Help:Bots",
    "Help:Bots/bn",
    "Help:Bots/br",
    "Help:Bots/ca",
    "Help:Bots/de",
    "Help:Bots/en",
    "Help:Bots/fr",
    "Help:Bots/mk",
    "Help:Bots/nb",
    "Help:Bots/oc",
    "Help:Bots/pl",
    "Help:Bots/scn",
    "Help:Bots/sv",
    "Help:Bots/ta",
    "Help:CSS",
    "Help:Choosing a microphone",
    "Help:Choosing a microphone/br",
    "Help:Choosing a microphone/de",
    "Help:Choosing a microphone/en",
    "Help:Choosing a microphone/eo",
    "Help:Choosing a microphone/es",
    "Help:Choosing a microphone/fr",
    "Help:Choosing a microphone/gl",
    "Help:Choosing a microphone/he",
    "Help:Choosing a microphone/ia",
    "Help:Choosing a microphone/ja",
    "Help:Choosing a microphone/mk",
    "Help:Choosing a microphone/nb",
    "Help:Choosing a microphone/oc",
    "Help:Choosing a microphone/pl",
    "Help:Choosing a microphone/pt-br",
    "Help:Choosing a microphone/scn",
    "Help:Choosing a microphone/sv",
    "Help:Configure your microphone",
    "Help:Configure your microphone/de",
    "Help:Configure your microphone/el",
    "Help:Configure your microphone/en",
    "Help:Configure your microphone/fr",
    "Help:Configure your microphone/gl",
    "Help:Configure your microphone/ia",
    "Help:Configure your microphone/ja",
    "Help:Configure your microphone/mk",
    "Help:Configure your microphone/nb",
    "Help:Configure your microphone/oc",
    "Help:Configure your microphone/pl",
    "Help:Configure your microphone/scn",
    "Help:Configure your microphone/sv",
    "Help:Configure your microphone/zh",
    "Help:Converting audios",
    "Help:Create your own lists",
    "Help:Create your own lists/br",
    "Help:Create your own lists/de",
    "Help:Create your own lists/en",
    "Help:Create your own lists/es",
    "Help:Create your own lists/fr",
    "Help:Create your own lists/he",
    "Help:Create your own lists/ig",
    "Help:Create your own lists/ja",
    "Help:Create your own lists/mk",
    "Help:Create your own lists/mni",
    "Help:Create your own lists/nb",
    "Help:Create your own lists/oc",
    "Help:Create your own lists/pt-br",
    "Help:Create your own lists/ru",
    "Help:Create your own lists/scn",
    "Help:Create your own lists/sv",
    "Help:Create your own lists/ta",
    "Help:Database structure",
    "Help:Documentation opérationelle Mediawiki",
    "Help:Documentation opérationelle Mediawiki/1.35",
    "Help:Download",
    "Help:Download-Commons-category",
    "Help:Download datasets",
    "Help:Download datasets/Header",
    "Help:Download datasets/Header/text",
    "Help:Download datasets/Header/text/de",
    "Help:Download datasets/Header/text/en",
    "Help:Download datasets/Header/text/fr",
    "Help:Download datasets/Header/text/mk",
    "Help:Download datasets/Header/text/sv",
    "Help:Download datasets/bn",
    "Help:Download datasets/de",
    "Help:Download datasets/en",
    "Help:Download datasets/mk",
    "Help:Download datasets/nb",
    "Help:Download datasets/oc",
    "Help:Download datasets/pl",
    "Help:Download datasets/pt-br",
    "Help:Download datasets/sv",
    "Help:Embed audio in HTML",
    "Help:Ethics",
    "Help:Homograph",
    "Help:Homographs",
    "Help:How to create a frequency list?",
    "Help:How to create a wordlist ?",
    "Help:How to embed audio in webpage?",
    "Help:How to embed audio in webpages?",
    "Help:Inpage",
    "Help:Interface",
    "Help:Interface/bn",
    "Help:Interface/br",
    "Help:Interface/de",
    "Help:Interface/en",
    "Help:Interface/eo",
    "Help:Interface/es",
    "Help:Interface/fr",
    "Help:Interface/gl",
    "Help:Interface/he",
    "Help:Interface/id",
    "Help:Interface/ja",
    "Help:Interface/mk",
    "Help:Interface/nb",
    "Help:Interface/oc",
    "Help:Interface/pl",
    "Help:Interface/ro",
    "Help:Interface/scn",
    "Help:Interface/sv",
    "Help:Interface/ta",
    "Help:Langtags",
    "Help:Langtags/br",
    "Help:Langtags/de",
    "Help:Langtags/en",
    "Help:Langtags/eo",
    "Help:Langtags/fr",
    "Help:Langtags/mk",
    "Help:Langtags/nb",
    "Help:Langtags/pl",
    "Help:Langtags/ru",
    "Help:List translation",
    "Help:Lists",
    "Help:Log in to Lingua Libre with Pywikibot",
    "Help:Main",
    "Help:Main/arq",
    "Help:Main/ba",
    "Help:Main/bn",
    "Help:Main/br",
    "Help:Main/ca",
    "Help:Main/da",
    "Help:Main/de",
    "Help:Main/el",
    "Help:Main/en",
    "Help:Main/eo",
    "Help:Main/es",
    "Help:Main/eu",
    "Help:Main/fr",
    "Help:Main/gl",
    "Help:Main/he",
    "Help:Main/hu",
    "Help:Main/ia",
    "Help:Main/id",
    "Help:Main/ja",
    "Help:Main/kaa",
    "Help:Main/ko",
    "Help:Main/lmo",
    "Help:Main/mk",
    "Help:Main/ms",
    "Help:Main/nb",
    "Help:Main/oc",
    "Help:Main/pl",
    "Help:Main/pt",
    "Help:Main/ro",
    "Help:Main/ru",
    "Help:Main/scn",
    "Help:Main/sv",
    "Help:Main/ta",
    "Help:Main/tokipona",
    "Help:Main/tr",
    "Help:Main/yue",
    "Help:Main/zh",
    "Help:OAuth",
    "Help:Oauth",
    "Help:Pywikibot",
    "Help:Querying Lingua Libre",
    "Help:Ratelimit",
    "Help:Ratelimits",
    "Help:RecordWizard manual",
    "Help:RecordWizard manual/br",
    "Help:RecordWizard manual/de",
    "Help:RecordWizard manual/en",
    "Help:RecordWizard manual/eo",
    "Help:RecordWizard manual/fr",
    "Help:RecordWizard manual/he",
    "Help:RecordWizard manual/it",
    "Help:RecordWizard manual/ja",
    "Help:RecordWizard manual/mk",
    "Help:RecordWizard manual/nb",
    "Help:RecordWizard manual/oc",
    "Help:RecordWizard manual/pl",
    "Help:RecordWizard manual/pt",
    "Help:RecordWizard manual/pt-br",
    "Help:RecordWizard manual/qu",
    "Help:RecordWizard manual/scn",
    "Help:RecordWizard manual/sv",
    "Help:Rename",
    "Help:Renaming",
    "Help:SPARQL",
    "Help:SPARQL/test",
    "Help:SPARQL (HAL)",
    "Help:SPARQL (intermediate)",
    "Help:SPARQL (lexeme)",
    "Help:SPARQL 2",
    "Help:SPARQL for languages of France",
    "Help:SPARQL for lexemes",
    "Help:SPARQL for maintenance",
    "Help:SoX",
    "Help:Sound library",
    "Help:Sparql",
    "Help:Swadesh",
    "Help:Swadesh lists",
    "Help:Why wordlists matter?",
    "Help:Wordlist?",
    "Help:Your first record",
    "Help:Your first record/br",
    "Help:Your first record/de",
    "Help:Your first record/en",
    "Help:Your first record/eo",
    "Help:Your first record/es",
    "Help:Your first record/fr",
    "Help:Your first record/gl",
    "Help:Your first record/ja",
    "Help:Your first record/ko",
    "Help:Your first record/mk",
    "Help:Your first record/nb",
    "Help:Your first record/oc",
    "Help:Your first record/pl",
    "Help:Your first record/ro",
    "Help:Your first record/ru",
    "Help:Your first record/scn",
    "Help:Your first record/sv",
    "Help:Your first record/tr"
    ]
};

// Export to global scope for browser access
if (typeof window !== 'undefined') {
    window.help = help;
}