const lingualibre = { 
    cleaner: function(inputList) {
            return inputList
                .filter(item => !item.includes('LinguaLibre:Administrators'))
                .filter(item => !item.includes('LinguaLibre:Babel'))
                .filter(item => !item.includes('LinguaLibre:Bureaucrats'))
                //.filter(item => !item.includes('LinguaLibre:Changelog'));
                .filter(item => !item.includes('LinguaLibre:Explore the sound library'))
                .filter(item => !item.includes('LinguaLibre:LiLiZip'))
                .filter(item => !item.includes('LinguaLibre:List of languages'))
                .filter(item => !item.includes('LinguaLibre:Pages'))
                .filter(item => !item.includes('LinguaLibre:Records'))
                .filter(item => !item.includes('LinguaLibre:Speakers'))
                .filter(item => !item.includes('LinguaLibre:Stat'))
                //.filter(item => !item.includes('LinguaLibre:About'))
                //.filter(item => !item.includes('LinguaLibre:Privacy'))
                .filter(item => !item.includes('LinguaLibre:Translation administrators'))
                .filter(item => !item.includes('Explore the sound library'))
                .filter(item => item !== 'LinguaLibre:Technical board')
                .filter(item => item !== 'LinguaLibre:Chat room')
                .filter(item => !/\/([a-z]{2,3}(-[a-z]{2,4})?)$/.test(item));
        },
    list : [
    "LinguaLibre:2022-2023 projection",
    "LinguaLibre:About",
    "LinguaLibre:About/as",
    "LinguaLibre:About/ba",
    "LinguaLibre:About/br",
    "LinguaLibre:About/da",
    "LinguaLibre:About/de",
    "LinguaLibre:About/en",
    "LinguaLibre:About/eo",
    "LinguaLibre:About/es",
    "LinguaLibre:About/eu",
    "LinguaLibre:About/fr",
    "LinguaLibre:About/gor",
    "LinguaLibre:About/he",
    "LinguaLibre:About/id",
    "LinguaLibre:About/is",
    "LinguaLibre:About/it",
    "LinguaLibre:About/ja",
    "LinguaLibre:About/kaa",
    "LinguaLibre:About/mk",
    "LinguaLibre:About/mnw",
    "LinguaLibre:About/ms",
    "LinguaLibre:About/my",
    "LinguaLibre:About/nb",
    "LinguaLibre:About/oc",
    "LinguaLibre:About/pl",
    "LinguaLibre:About/pt",
    "LinguaLibre:About/ro",
    "LinguaLibre:About/ru",
    "LinguaLibre:About/scn",
    "LinguaLibre:About/shn",
    "LinguaLibre:About/sv",
    "LinguaLibre:About/te",
    "LinguaLibre:About/tokipona",
    "LinguaLibre:About/tr",
    "LinguaLibre:About/yue",
    "LinguaLibre:Administrators",
    "LinguaLibre:Administrators' noticeboard",
    "LinguaLibre:Administrators' noticeboard/Header",
    "LinguaLibre:Administrators' noticeboard/Header/text",
    "LinguaLibre:Administrators' noticeboard/Header/text/bn",
    "LinguaLibre:Administrators' noticeboard/Header/text/de",
    "LinguaLibre:Administrators' noticeboard/Header/text/en",
    "LinguaLibre:Administrators' noticeboard/Header/text/fr",
    "LinguaLibre:Administrators' noticeboard/Header/text/he",
    "LinguaLibre:Administrators' noticeboard/Header/text/ja",
    "LinguaLibre:Administrators' noticeboard/Header/text/mk",
    "LinguaLibre:Administrators' noticeboard/Header/text/oc",
    "LinguaLibre:Administrators' noticeboard/Header/text/scn",
    "LinguaLibre:Administrators' noticeboard/Header/text/sv",
    "LinguaLibre:Administrators/bn",
    "LinguaLibre:Administrators/de",
    "LinguaLibre:Administrators/en",
    "LinguaLibre:Administrators/eo",
    "LinguaLibre:Administrators/fr",
    "LinguaLibre:Administrators/ja",
    "LinguaLibre:Administrators/mk",
    "LinguaLibre:Administrators/oc",
    "LinguaLibre:Administrators/pl",
    "LinguaLibre:Administrators/scn",
    "LinguaLibre:Administrators/sv",
    "LinguaLibre:Administrators/te",
    "LinguaLibre:Admins",
    "LinguaLibre:Apps",
    "LinguaLibre:Atelier de contribution 06/12/2018",
    "LinguaLibre:AutoWikiBrowser/Script",
    "LinguaLibre:AutoWikiBrowser/Typos",
    "LinguaLibre:Autoconfirmed users",
    "LinguaLibre:Babel",
    "LinguaLibre:Babel/text",
    "LinguaLibre:Babel/text/bn",
    "LinguaLibre:Babel/text/br",
    "LinguaLibre:Babel/text/de",
    "LinguaLibre:Babel/text/en",
    "LinguaLibre:Babel/text/fr",
    "LinguaLibre:Babel/text/he",
    "LinguaLibre:Babel/text/mk",
    "LinguaLibre:Babel/text/ms",
    "LinguaLibre:Babel/text/nb",
    "LinguaLibre:Babel/text/oc",
    "LinguaLibre:Babel/text/scn",
    "LinguaLibre:Babel/text/sv",
    "LinguaLibre:Babel/text/te",
    "LinguaLibre:Babilejo",
    "LinguaLibre:Bistro",
    "LinguaLibre:Bot",
    "LinguaLibre:Bot/form",
    "LinguaLibre:Bot/intro",
    "LinguaLibre:Bureaucrats",
    "LinguaLibre:Bureaucrats/Header",
    "LinguaLibre:Bureaucrats/Header/text",
    "LinguaLibre:Bureaucrats/Header/text/de",
    "LinguaLibre:Bureaucrats/Header/text/en",
    "LinguaLibre:Bureaucrats/Header/text/fr",
    "LinguaLibre:Bureaucrats/Header/text/mk",
    "LinguaLibre:Bureaucrats/Header/text/oc",
    "LinguaLibre:Bureaucrats/Header/text/sv",
    "LinguaLibre:Bureaucrats/Header/text/yue",
    "LinguaLibre:Bureaucrats/bn",
    "LinguaLibre:Bureaucrats/br",
    "LinguaLibre:Bureaucrats/de",
    "LinguaLibre:Bureaucrats/en",
    "LinguaLibre:Bureaucrats/eo",
    "LinguaLibre:Bureaucrats/fr",
    "LinguaLibre:Bureaucrats/ja",
    "LinguaLibre:Bureaucrats/mk",
    "LinguaLibre:Bureaucrats/nb",
    "LinguaLibre:Bureaucrats/oc",
    "LinguaLibre:Bureaucrats/scn",
    "LinguaLibre:Bureaucrats/sv",
    "LinguaLibre:Changelog",
    "LinguaLibre:Changelog/de",
    "LinguaLibre:Changelog/en",
    "LinguaLibre:Changelog/fr",
    "LinguaLibre:Changelog/ia",
    "LinguaLibre:Changelog/ja",
    "LinguaLibre:Changelog/mk",
    "LinguaLibre:Changelog/oc",
    "LinguaLibre:Changelog/scn",
    "LinguaLibre:Chat Room",
    "LinguaLibre:Chat room",
    "LinguaLibre:Chat room/Annonce 100 000",
    "LinguaLibre:Chat room/Archives/2018",
    "LinguaLibre:Chat room/Archives/2019",
    "LinguaLibre:Chat room/Archives/2020",
    "LinguaLibre:Chat room/Archives/2021",
    "LinguaLibre:Chat room/Archives/2022",
    "LinguaLibre:Chat room/Archives/2023",
    "LinguaLibre:Chat room/FAQ",
    "LinguaLibre:Chat room/FAQ/text",
    "LinguaLibre:Chat room/FAQ/text/br",
    "LinguaLibre:Chat room/FAQ/text/de",
    "LinguaLibre:Chat room/FAQ/text/en",
    "LinguaLibre:Chat room/FAQ/text/fr",
    "LinguaLibre:Chat room/FAQ/text/ia",
    "LinguaLibre:Chat room/FAQ/text/mk",
    "LinguaLibre:Chat room/FAQ/text/oc",
    "LinguaLibre:Chat room/FAQ/text/sv",
    "LinguaLibre:Chat room/Header",
    "LinguaLibre:Chat room/Header/text",
    "LinguaLibre:Chat room/Header/text/de",
    "LinguaLibre:Chat room/Header/text/en",
    "LinguaLibre:Chat room/Header/text/fr",
    "LinguaLibre:Chat room/Header/text/ja",
    "LinguaLibre:Chat room/Header/text/mk",
    "LinguaLibre:Chat room/Header/text/oc",
    "LinguaLibre:Chat room/Header/text/pl",
    "LinguaLibre:Chat room/Header/text/sv",
    "LinguaLibre:Chat room/Header/text/th",
    "LinguaLibre:Chat room/Header/text/yue",
    "LinguaLibre:Chat room/en",
    "LinguaLibre:Chat room/hyw",
    "LinguaLibre:Chat room/mk",
    "LinguaLibre:Chat room/pl",
    "LinguaLibre:Chat room/yue",
    "LinguaLibre:Citations",
    "LinguaLibre:Community",
    "LinguaLibre:Community/bn",
    "LinguaLibre:Community/br",
    "LinguaLibre:Community/de",
    "LinguaLibre:Community/en",
    "LinguaLibre:Community/fr",
    "LinguaLibre:Community/ia",
    "LinguaLibre:Community/kaa",
    "LinguaLibre:Community/mk",
    "LinguaLibre:Community/oc",
    "LinguaLibre:Community/pl",
    "LinguaLibre:Community/scn",
    "LinguaLibre:Community/sv",
    "LinguaLibre:Coordination",
    "LinguaLibre:Coordination/ANR",
    "LinguaLibre:Copyrights",
    "LinguaLibre:Copyrights/bg",
    "LinguaLibre:Copyrights/br",
    "LinguaLibre:Copyrights/de",
    "LinguaLibre:Copyrights/en",
    "LinguaLibre:Copyrights/en-ca",
    "LinguaLibre:Copyrights/fr",
    "LinguaLibre:Copyrights/he",
    "LinguaLibre:Copyrights/mk",
    "LinguaLibre:Copyrights/ms",
    "LinguaLibre:Copyrights/oc",
    "LinguaLibre:Copyrights/pl",
    "LinguaLibre:Copyrights/ru",
    "LinguaLibre:Copyrights/sv",
    "LinguaLibre:Events",
    "LinguaLibre:Events/2016-2017 meetings",
    "LinguaLibre:Events/2018",
    "LinguaLibre:Events/2019",
    "LinguaLibre:Events/2020",
    "LinguaLibre:Events/2020 Occitans-Gascons",
    "LinguaLibre:Events/2021 ContriLing",
    "LinguaLibre:Events/2021 ContribuLing",
    "LinguaLibre:Events/2021 Internationa call",
    "LinguaLibre:Events/2021 TAL ContriLing",
    "LinguaLibre:Events/2021 UNILEX-Lingualibre",
    "LinguaLibre:Events/2021 Wikimedia Wikimeet India",
    "LinguaLibre:Events/2022.06 Lingualibre online meetup",
    "LinguaLibre:Events/2022.06 Lingualibre online meetup/de",
    "LinguaLibre:Events/2022.06 Lingualibre online meetup/en",
    "LinguaLibre:Events/2022.06 Lingualibre online meetup/nb",
    "LinguaLibre:Events/2022 Forom des langues",
    "LinguaLibre:Events/2022 Hackathon",
    "LinguaLibre:Events/2022 LREC",
    "LinguaLibre:Events/2022 Lingualibre-Surui workshop",
    "LinguaLibre:Events/2022 Lingualibre-Surui workshop/de",
    "LinguaLibre:Events/2022 Lingualibre-Surui workshop/en",
    "LinguaLibre:Events/2022 WikiConvention",
    "LinguaLibre:Events/2022 Wikicamp",
    "LinguaLibre:Events/2022 Wikimania",
    "LinguaLibre:Events/2022 campaign",
    "LinguaLibre:Events/2023 Contribuling",
    "LinguaLibre:Events/2023 Editathon",
    "LinguaLibre:Events/2023 Wikimania",
    "LinguaLibre:Events/2023 Wikimedia Hackathon",
    "LinguaLibre:Events/2024 Hackathon",
    "LinguaLibre:Events/2024 LREC",
    "LinguaLibre:Events/Archives",
    "LinguaLibre:Events/Gallery",
    "LinguaLibre:Events/Hackathon 15-16 Décembre",
    "LinguaLibre:Events/Hackathon 15-16 décembre 2018",
    "LinguaLibre:Events/Hackathon juillet 2021",
    "LinguaLibre:Events/Patrol assistance tool prototyping project",
    "LinguaLibre:Events/Patrol assistance tool prototyping project/Intro",
    "LinguaLibre:Events/Patrol assistance tool prototyping project/Intro/text",
    "LinguaLibre:Events/Patrol assistance tool prototyping project/Intro/text/de",
    "LinguaLibre:Events/Patrol assistance tool prototyping project/Intro/text/en",
    "LinguaLibre:Events/Patrol assistance tool prototyping project/Intro/text/fr",
    "LinguaLibre:Events/Patrol assistance tool prototyping project/Intro/text/oc",
    "LinguaLibre:Events/Patrol assistance tool prototyping project/de",
    "LinguaLibre:Events/Patrol assistance tool prototyping project/en",
    "LinguaLibre:Events/Patrol assistance tool prototyping project/fr",
    "LinguaLibre:Events/Patrol assistance tool prototyping project/oc",
    "LinguaLibre:Events/Patrol assistance tool prototyping project/sv",
    "LinguaLibre:Events/Program",
    "LinguaLibre:Events/Winter 2021-2022 Public Relations Campaign",
    "LinguaLibre:Explore the sound library",
    "LinguaLibre:Explore the sound library/ar",
    "LinguaLibre:Explore the sound library/ba",
    "LinguaLibre:Explore the sound library/bg",
    "LinguaLibre:Explore the sound library/bn",
    "LinguaLibre:Explore the sound library/br",
    "LinguaLibre:Explore the sound library/de",
    "LinguaLibre:Explore the sound library/el",
    "LinguaLibre:Explore the sound library/en",
    "LinguaLibre:Explore the sound library/eo",
    "LinguaLibre:Explore the sound library/es",
    "LinguaLibre:Explore the sound library/eu",
    "LinguaLibre:Explore the sound library/fr",
    "LinguaLibre:Explore the sound library/gl",
    "LinguaLibre:Explore the sound library/gor",
    "LinguaLibre:Explore the sound library/he",
    "LinguaLibre:Explore the sound library/hi",
    "LinguaLibre:Explore the sound library/id",
    "LinguaLibre:Explore the sound library/kaa",
    "LinguaLibre:Explore the sound library/lmo",
    "LinguaLibre:Explore the sound library/mk",
    "LinguaLibre:Explore the sound library/mnw",
    "LinguaLibre:Explore the sound library/ms",
    "LinguaLibre:Explore the sound library/oc",
    "LinguaLibre:Explore the sound library/pl",
    "LinguaLibre:Explore the sound library/pnb",
    "LinguaLibre:Explore the sound library/ru",
    "LinguaLibre:Explore the sound library/scn",
    "LinguaLibre:Explore the sound library/sv",
    "LinguaLibre:Explore the sound library/ta",
    "LinguaLibre:Explore the sound library/te",
    "LinguaLibre:Explore the sound library/tokipona",
    "LinguaLibre:Explore the sound library/tr",
    "LinguaLibre:Explore the sound library/ur",
    "LinguaLibre:Explore the sound library/yue",
    "LinguaLibre:Explore the sound library/zgh",
    "LinguaLibre:Explore the sound library/zh",
    "LinguaLibre:Feedbacks",
    "LinguaLibre:Formations CCWL",
    "LinguaLibre:Grants",
    "LinguaLibre:Hackathon",
    "LinguaLibre:History",
    "LinguaLibre:Interested communities",
    "LinguaLibre:Jargon",
    "LinguaLibre:Language codes systems used across LinguaLibre",
    "LinguaLibre:LiLiZip",
    "LinguaLibre:LiLiZip/run",
    "LinguaLibre:LinguaZip",
    "LinguaLibre:LinguaZip/run",
    "LinguaLibre:List of languages",
    "LinguaLibre:List of languages/bn",
    "LinguaLibre:List of languages/br",
    "LinguaLibre:List of languages/de",
    "LinguaLibre:List of languages/en",
    "LinguaLibre:List of languages/fr",
    "LinguaLibre:List of languages/gor",
    "LinguaLibre:List of languages/he",
    "LinguaLibre:List of languages/ia",
    "LinguaLibre:List of languages/id",
    "LinguaLibre:List of languages/kaa",
    "LinguaLibre:List of languages/mk",
    "LinguaLibre:List of languages/oc",
    "LinguaLibre:List of languages/pl",
    "LinguaLibre:List of languages/ru",
    "LinguaLibre:List of languages/scn",
    "LinguaLibre:List of languages/sv",
    "LinguaLibre:Mailing",
    "LinguaLibre:Main",
    "LinguaLibre:Main Page",
    "LinguaLibre:Main Page/text",
    "LinguaLibre:Main Page/text/ar",
    "LinguaLibre:Main Page/text/ba",
    "LinguaLibre:Main Page/text/ban",
    "LinguaLibre:Main Page/text/be",
    "LinguaLibre:Main Page/text/bg",
    "LinguaLibre:Main Page/text/bn",
    "LinguaLibre:Main Page/text/br",
    "LinguaLibre:Main Page/text/ca",
    "LinguaLibre:Main Page/text/de",
    "LinguaLibre:Main Page/text/dtp",
    "LinguaLibre:Main Page/text/el",
    "LinguaLibre:Main Page/text/en",
    "LinguaLibre:Main Page/text/eo",
    "LinguaLibre:Main Page/text/es",
    "LinguaLibre:Main Page/text/eu",
    "LinguaLibre:Main Page/text/fa",
    "LinguaLibre:Main Page/text/fi",
    "LinguaLibre:Main Page/text/fr",
    "LinguaLibre:Main Page/text/frc",
    "LinguaLibre:Main Page/text/ga",
    "LinguaLibre:Main Page/text/gl",
    "LinguaLibre:Main Page/text/he",
    "LinguaLibre:Main Page/text/hi",
    "LinguaLibre:Main Page/text/hyw",
    "LinguaLibre:Main Page/text/id",
    "LinguaLibre:Main Page/text/ig",
    "LinguaLibre:Main Page/text/it",
    "LinguaLibre:Main Page/text/ja",
    "LinguaLibre:Main Page/text/kaa",
    "LinguaLibre:Main Page/text/ko",
    "LinguaLibre:Main Page/text/lfn",
    "LinguaLibre:Main Page/text/lmo",
    "LinguaLibre:Main Page/text/lt",
    "LinguaLibre:Main Page/text/mk",
    "LinguaLibre:Main Page/text/ml",
    "LinguaLibre:Main Page/text/mnw",
    "LinguaLibre:Main Page/text/ms",
    "LinguaLibre:Main Page/text/my",
    "LinguaLibre:Main Page/text/nb",
    "LinguaLibre:Main Page/text/oc",
    "LinguaLibre:Main Page/text/pl",
    "LinguaLibre:Main Page/text/pnb",
    "LinguaLibre:Main Page/text/pt",
    "LinguaLibre:Main Page/text/pt-br",
    "LinguaLibre:Main Page/text/ro",
    "LinguaLibre:Main Page/text/ru",
    "LinguaLibre:Main Page/text/sat",
    "LinguaLibre:Main Page/text/scn",
    "LinguaLibre:Main Page/text/sdc",
    "LinguaLibre:Main Page/text/shn",
    "LinguaLibre:Main Page/text/sk",
    "LinguaLibre:Main Page/text/sv",
    "LinguaLibre:Main Page/text/ta",
    "LinguaLibre:Main Page/text/te",
    "LinguaLibre:Main Page/text/tg",
    "LinguaLibre:Main Page/text/th",
    "LinguaLibre:Main Page/text/tly",
    "LinguaLibre:Main Page/text/tokipona",
    "LinguaLibre:Main Page/text/tr",
    "LinguaLibre:Main Page/text/tt",
    "LinguaLibre:Main Page/text/uk",
    "LinguaLibre:Main Page/text/uz",
    "LinguaLibre:Main Page/text/vi",
    "LinguaLibre:Main Page/text/yue",
    "LinguaLibre:Main Page/text/zgh",
    "LinguaLibre:Main Page/text/zh",
    "LinguaLibre:Main Page/text/zh-cn",
    "LinguaLibre:Main Page/text/zh-hant",
    "LinguaLibre:Misleading items",
    "LinguaLibre:Misleading items/Berrely 20210802",
    "LinguaLibre:Misleading items/Camara aminata 20191116",
    "LinguaLibre:Misleading items/Ives 20190208",
    "LinguaLibre:Misleading items/Lepticed7 20181219",
    "LinguaLibre:Misleading items/Lepticed7 20190315",
    "LinguaLibre:Misleading items/Modjou 20190520",
    "LinguaLibre:Misleading items/Psychoslave 20210703",
    "LinguaLibre:Misleading items/WikiLucas00 20191219",
    "LinguaLibre:Misleading items/WikiLucas00 20191220",
    "LinguaLibre:Misleading items/de",
    "LinguaLibre:Misleading items/en",
    "LinguaLibre:Misleading items/fr",
    "LinguaLibre:Misleading items/mk",
    "LinguaLibre:Misleading items/nb",
    "LinguaLibre:Misleading items/oc",
    "LinguaLibre:Misleading items/sv",
    "LinguaLibre:Pages",
    "LinguaLibre:Privacy policy",
    "LinguaLibre:Privacy policy/ba",
    "LinguaLibre:Privacy policy/bn",
    "LinguaLibre:Privacy policy/br",
    "LinguaLibre:Privacy policy/de",
    "LinguaLibre:Privacy policy/en",
    "LinguaLibre:Privacy policy/fr",
    "LinguaLibre:Privacy policy/lmo",
    "LinguaLibre:Privacy policy/mk",
    "LinguaLibre:Privacy policy/oc",
    "LinguaLibre:Privacy policy/pl",
    "LinguaLibre:Privacy policy/ru",
    "LinguaLibre:Privacy policy/scn",
    "LinguaLibre:Privacy policy/sv",
    "LinguaLibre:Projet de développement d'outils d'aide à la patrouille",
    "LinguaLibre:Ratelimit",
    "LinguaLibre:Ratelimits",
    "LinguaLibre:Records",
    "LinguaLibre:Records/bn",
    "LinguaLibre:Records/br",
    "LinguaLibre:Records/de",
    "LinguaLibre:Records/en",
    "LinguaLibre:Records/eo",
    "LinguaLibre:Records/fr",
    "LinguaLibre:Records/ja",
    "LinguaLibre:Records/mk",
    "LinguaLibre:Records/mnw",
    "LinguaLibre:Records/nb",
    "LinguaLibre:Records/oc",
    "LinguaLibre:Records/pl",
    "LinguaLibre:Records/ru",
    "LinguaLibre:Records/sv",
    "LinguaLibre:Records/ta",
    "LinguaLibre:Records/yue",
    "LinguaLibre:Roles",
    "LinguaLibre:Réunions",
    "LinguaLibre:Réunions/2016-2017 meetings",
    "LinguaLibre:Réunions/2018",
    "LinguaLibre:Réunions/2018/3-11",
    "LinguaLibre:Réunions/2020",
    "LinguaLibre:Réunions/2020/20-01",
    "LinguaLibre:Réunions/2020/4-12",
    "LinguaLibre:Réunions/2021",
    "LinguaLibre:Réunions/2021/14-09",
    "LinguaLibre:Sandbox",
    "LinguaLibre:Sparql",
    "LinguaLibre:Speakers",
    "LinguaLibre:Speakers/bn",
    "LinguaLibre:Speakers/br",
    "LinguaLibre:Speakers/de",
    "LinguaLibre:Speakers/en",
    "LinguaLibre:Speakers/en-ca",
    "LinguaLibre:Speakers/eo",
    "LinguaLibre:Speakers/es",
    "LinguaLibre:Speakers/fr",
    "LinguaLibre:Speakers/ja",
    "LinguaLibre:Speakers/kaa",
    "LinguaLibre:Speakers/kab",
    "LinguaLibre:Speakers/mk",
    "LinguaLibre:Speakers/ms",
    "LinguaLibre:Speakers/nb",
    "LinguaLibre:Speakers/oc",
    "LinguaLibre:Speakers/pl",
    "LinguaLibre:Speakers/sv",
    "LinguaLibre:Statistics",
    "LinguaLibre:Stats",
    "LinguaLibre:Stats/Languages",
    "LinguaLibre:Stats/Languages/ba",
    "LinguaLibre:Stats/Languages/bn",
    "LinguaLibre:Stats/Languages/br",
    "LinguaLibre:Stats/Languages/de",
    "LinguaLibre:Stats/Languages/el",
    "LinguaLibre:Stats/Languages/en",
    "LinguaLibre:Stats/Languages/eo",
    "LinguaLibre:Stats/Languages/eu",
    "LinguaLibre:Stats/Languages/fr",
    "LinguaLibre:Stats/Languages/gl",
    "LinguaLibre:Stats/Languages/he",
    "LinguaLibre:Stats/Languages/id",
    "LinguaLibre:Stats/Languages/ig",
    "LinguaLibre:Stats/Languages/kaa",
    "LinguaLibre:Stats/Languages/mk",
    "LinguaLibre:Stats/Languages/ms",
    "LinguaLibre:Stats/Languages/oc",
    "LinguaLibre:Stats/Languages/pl",
    "LinguaLibre:Stats/Languages/ru",
    "LinguaLibre:Stats/Languages/scn",
    "LinguaLibre:Stats/Languages/sv",
    "LinguaLibre:Stats/Languages/ta",
    "LinguaLibre:Stats/Languages/te",
    "LinguaLibre:Stats/Languages/tokipona",
    "LinguaLibre:Stats/Languages/yue",
    "LinguaLibre:Stats/Menu",
    "LinguaLibre:Stats/Menu/text",
    "LinguaLibre:Stats/Menu/text/bn",
    "LinguaLibre:Stats/Menu/text/br",
    "LinguaLibre:Stats/Menu/text/de",
    "LinguaLibre:Stats/Menu/text/en",
    "LinguaLibre:Stats/Menu/text/eo",
    "LinguaLibre:Stats/Menu/text/es",
    "LinguaLibre:Stats/Menu/text/fr",
    "LinguaLibre:Stats/Menu/text/he",
    "LinguaLibre:Stats/Menu/text/id",
    "LinguaLibre:Stats/Menu/text/mk",
    "LinguaLibre:Stats/Menu/text/ms",
    "LinguaLibre:Stats/Menu/text/nb",
    "LinguaLibre:Stats/Menu/text/oc",
    "LinguaLibre:Stats/Menu/text/pl",
    "LinguaLibre:Stats/Menu/text/ru",
    "LinguaLibre:Stats/Menu/text/scn",
    "LinguaLibre:Stats/Menu/text/sv",
    "LinguaLibre:Stats/Menu/text/te",
    "LinguaLibre:Stats/Menu/text/tr",
    "LinguaLibre:Stats/Menu/text/yue",
    "LinguaLibre:Stats/Speakers",
    "LinguaLibre:Stats/Speakers/ar",
    "LinguaLibre:Stats/Speakers/ba",
    "LinguaLibre:Stats/Speakers/bn",
    "LinguaLibre:Stats/Speakers/br",
    "LinguaLibre:Stats/Speakers/de",
    "LinguaLibre:Stats/Speakers/el",
    "LinguaLibre:Stats/Speakers/en",
    "LinguaLibre:Stats/Speakers/eo",
    "LinguaLibre:Stats/Speakers/fr",
    "LinguaLibre:Stats/Speakers/id",
    "LinguaLibre:Stats/Speakers/kaa",
    "LinguaLibre:Stats/Speakers/mk",
    "LinguaLibre:Stats/Speakers/ms",
    "LinguaLibre:Stats/Speakers/nb",
    "LinguaLibre:Stats/Speakers/oc",
    "LinguaLibre:Stats/Speakers/pl",
    "LinguaLibre:Stats/Speakers/pt-br",
    "LinguaLibre:Stats/Speakers/ro",
    "LinguaLibre:Stats/Speakers/ru",
    "LinguaLibre:Stats/Speakers/sv",
    "LinguaLibre:Stats/Speakers/tokipona",
    "LinguaLibre:Stats/Speakers/zgh",
    "LinguaLibre:Stats/Time",
    "LinguaLibre:Stats/Time/ba",
    "LinguaLibre:Stats/Time/bn",
    "LinguaLibre:Stats/Time/br",
    "LinguaLibre:Stats/Time/de",
    "LinguaLibre:Stats/Time/el",
    "LinguaLibre:Stats/Time/en",
    "LinguaLibre:Stats/Time/en-gb",
    "LinguaLibre:Stats/Time/eo",
    "LinguaLibre:Stats/Time/fr",
    "LinguaLibre:Stats/Time/id",
    "LinguaLibre:Stats/Time/kaa",
    "LinguaLibre:Stats/Time/mk",
    "LinguaLibre:Stats/Time/mni",
    "LinguaLibre:Stats/Time/ms",
    "LinguaLibre:Stats/Time/nb",
    "LinguaLibre:Stats/Time/oc",
    "LinguaLibre:Stats/Time/pl",
    "LinguaLibre:Stats/Time/pt-br",
    "LinguaLibre:Stats/Time/ro",
    "LinguaLibre:Stats/Time/ru",
    "LinguaLibre:Stats/Time/scn",
    "LinguaLibre:Stats/Time/sv",
    "LinguaLibre:Stats/Time/te",
    "LinguaLibre:Stats/Time/tokipona",
    "LinguaLibre:Stats/Time/ur",
    "LinguaLibre:Stats/ast",
    "LinguaLibre:Stats/ba",
    "LinguaLibre:Stats/ban",
    "LinguaLibre:Stats/bcl",
    "LinguaLibre:Stats/bn",
    "LinguaLibre:Stats/br",
    "LinguaLibre:Stats/ca",
    "LinguaLibre:Stats/de",
    "LinguaLibre:Stats/el",
    "LinguaLibre:Stats/en",
    "LinguaLibre:Stats/eo",
    "LinguaLibre:Stats/es",
    "LinguaLibre:Stats/fr",
    "LinguaLibre:Stats/gl",
    "LinguaLibre:Stats/gor",
    "LinguaLibre:Stats/he",
    "LinguaLibre:Stats/id",
    "LinguaLibre:Stats/ig",
    "LinguaLibre:Stats/ja",
    "LinguaLibre:Stats/kaa",
    "LinguaLibre:Stats/lmo",
    "LinguaLibre:Stats/mk",
    "LinguaLibre:Stats/mni",
    "LinguaLibre:Stats/ms",
    "LinguaLibre:Stats/oc",
    "LinguaLibre:Stats/pl",
    "LinguaLibre:Stats/ro",
    "LinguaLibre:Stats/ru",
    "LinguaLibre:Stats/scn",
    "LinguaLibre:Stats/sv",
    "LinguaLibre:Stats/te",
    "LinguaLibre:Stats/tokipona",
    "LinguaLibre:Stats/tr",
    "LinguaLibre:Stats/uk",
    "LinguaLibre:Stats/yue",
    "LinguaLibre:Stats/zgh",
    "LinguaLibre:Stats/zh",
    "LinguaLibre:TB",
    "LinguaLibre:Technical Board",
    "LinguaLibre:Technical board",
    "LinguaLibre:Technical board/Audio click bug",
    "LinguaLibre:Technical board/Flash Technical News",
    "LinguaLibre:Technical board/Header",
    "LinguaLibre:Technical board/Header/text",
    "LinguaLibre:Technical board/Header/text/br",
    "LinguaLibre:Technical board/Header/text/de",
    "LinguaLibre:Technical board/Header/text/en",
    "LinguaLibre:Technical board/Header/text/fr",
    "LinguaLibre:Technical board/Header/text/id",
    "LinguaLibre:Technical board/Header/text/mk",
    "LinguaLibre:Technical board/Header/text/oc",
    "LinguaLibre:Technical board/Header/text/sv",
    "LinguaLibre:Technical board/News",
    "LinguaLibre:Technical board/Reports/2021/First progress report with WikiValley and VIGNERON",
    "LinguaLibre:Technical board/Reports/2021/Problèmes dans la mise à jour des statistiques",
    "LinguaLibre:Technical board/Reports/2021/Wikidata Lexemes & Lingua Libre coordination assessment",
    "LinguaLibre:Technical board/intro",
    "LinguaLibre:Text of Creative Commons Attribution-ShareAlike 4.0 International License",
    "LinguaLibre:Text of the Creative Commons Public Domain Dedication",
    "LinguaLibre:Translation administrators",
    "LinguaLibre:Translation administrators/bn",
    "LinguaLibre:Translation administrators/de",
    "LinguaLibre:Translation administrators/en",
    "LinguaLibre:Translation administrators/fr",
    "LinguaLibre:Translation administrators/mk",
    "LinguaLibre:Translation administrators/nb",
    "LinguaLibre:Translation administrators/oc",
    "LinguaLibre:Translation administrators/scn",
    "LinguaLibre:Translation administrators/sv",
    "LinguaLibre:Translation administrators/ta",
    "LinguaLibre:User rights",
    "LinguaLibre:User rights/br",
    "LinguaLibre:User rights/de",
    "LinguaLibre:User rights/en",
    "LinguaLibre:User rights/fr",
    "LinguaLibre:User rights/nb",
    "LinguaLibre:User rights/zgh",
    "LinguaLibre:Users",
    "LinguaLibre:Weekly updates",
    "LinguaLibre:Wiki Audio Walk",
    "LinguaLibre:Wiki Audio Walk 2025",
    "LinguaLibre:Wiki Audio Walk 2025/Kcg",
    "LinguaLibre:Wikidata",
    "LinguaLibre:Wikivalley",
    "LinguaLibre:Workshops",
    "LinguaLibre:संवाद-चर्चा दालन"
    ]
};

// Export to global scope for browser access
if (typeof window !== 'undefined') {
    window.lingualibre = lingualibre;
}