const template = { 
    cleaner: function(inputList) {
        const keepList = [
            //'Template:-',
            // 'Template:100k barnstar',
            // 'Template:2020 Coolest tool award',
            // 'Template:50k barnstar',
            //'Template:=',
            //'Template:Anchor',
            // 'Template:Audio Error Button',
            //'Template:Autopatrolled',
            //'Template:Autotranslate',
            //'Template:BCP47',
            //'Template:BUser',
            //'Template:Black',
            'Template:Bot cycle',
            'Template:Bot steps',
            //'Template:CURRENTCONTENTLANGUAGE',
            //'Template:Cc-by-sa-4.0',
            //'Template:Clear',
            //'Template:Clr',
            //'Template:Clickable button',
            //'Template:Clickable button 2',
            //'Template:Clickable button 3',
            //'Template:Col-2',
            //'Template:Colapse',
            //'Template:Collapse',
            //'Template:Collapse Templates',
            //'Template:Collapse templates',
            //'Template:Colon',
            //'Template:Color',
            //'Template:ColorFrame',
            //'Template:Colored box',
            //'Template:Column-gap',
            //'Template:Column-rule',
            //'Template:Column-width',
            //'Template:DataViz',
            //'Template:Dir',
            //'Template:Div col',
            //'Template:Div col end',
            //'Template:Documentation',
            //'Template:Documentation subpage',
            //'Template:Done',
            //'Template:Draft',
            //'Template:En',
            //'Template:Exclusion-list-link',
            //'Template:Exclusion list header',
            //'Template:Fallback',
            //'Template:Flatlist',
            //'Template:Fmbox',
            //'Template:Fr',
            // 'Template:GT',
            'Template:Gentle ramp',
            //'Template:Grants table',
            // 'Template:Help',
            'Template:Helps',
            'Template:Hermite Dave',
            //'Template:High-use',
            //'Template:IsDocSubpage',
            //'Template:LINGUALEX license', // deleted
            //'Template:Label',
            //'Template:Lang-CR',
            //'Template:LangSwitch',
            //'Template:Languageicon',
            //'Template:LanguagesGallery',
            //'Template:Laugh',
            //'Template:LexemeQueriesGenerator',
            //'Template:LinguaLex licence',
            //'Template:LinguaLibre scripts',
            //'Template:Lingua Libre scripts',
            //'Template:Ll',
            //'Template:Local list license',
            //'Template:Localized link',
            //'Template:Lorem ipsum',
            //'Template:Lua',
            //'Template:Module other',
            //'Template:Module rating',
            //'Template:Move',
            //'Template:Navbox',
            //'Template:Notif',
            //'Template:Olafbot-exclusion',
            //'Template:Olafbot-wikt',
            //'Template:Ombox',
            //'Template:Ongoing',
            //'Template:Oppose',
            //'Template:PP-template',
            //'Template:PR steps',
            //'Template:Pagelang',
            //'Template:Para',
            //'Template:Pause',
            //'Template:PedagoWikiCode',
            //'Template:Ping',
            //'Template:Plainlist',
            //'Template:Pp-meta',
            //'Template:Pp-template',
            //'Template:Pre2',
            'Template:Projects',
            //'Template:Property',
            //'Template:Purge',
            //'Template:Random number',
            //'Template:Rec',
            'Template:Recommended lists',
            'Template:Record ribbon',
            //'Template:Reply to',
            //'Template:SOFTREDIRECT',
            'Template:SOTM',
            'Template:SOTY',
            'Template:SUBTLEX-PT',
            'Template:SUBTLEX-CH',
            //'Template:Sandbox other',
            //'Template:Shared Template Warning',
            //'Template:Shortcut caption',
            //'Template:Skip',
            //'Template:Smile',
            //'Template:Soft redirect',
            //'Template:Sourire',
            //'Template:Sparql2data',
            'Template:Speaker of the month',
            'Template:Speaker of the year',
            'Template:Speakers category',
            //'Template:Str left',
            //'Template:Support',
            //'Template:SwitchLang',
            //'Template:TNT',
            'Template:Technicals',
            //'Template:Templ',
            //'Template:TemplateDataHeader',
            //'Template:Template other',
            //'Template:Template shortcut',
            //'Template:Tl',
            //'Template:Tlf',
            //'Template:Tlp',
            //'Template:Tlsp',
            //'Template:Tlx',
            //'Template:Tmpl',
            //'Template:To ISO639-2',
            'Template:To iso 639-2',
            'Template:To iso 639-3',
            //'Template:Transclude',
            //'Template:Translatable',
            //'Template:Translatable template',
            //'Template:Translate',
            //'Template:Trim',
            // 'Template:UNILEX license',
            //'Template:User SUL Box',
            //'Template:User details',
            'Template:User first 500k',
            //'Template:User info',
            //'Template:User link',
            //'Template:User ratelimit',
            'Template:User records-acy',
            'Template:User records-ami',
            'Template:User records-ara',
            'Template:User records-ban',
            'Template:User records-bcl',
            'Template:User records-bel',
            'Template:User records-ben',
            'Template:User records-bik',
            'Template:User records-blk',
            'Template:User records-cat',
            'Template:User records-cmn',
            'Template:User records-deu',
            'Template:User records-ell',
            'Template:User records-eng',
            'Template:User records-epo',
            'Template:User records-eus',
            'Template:User records-fra',
            'Template:User records-glg',
            'Template:User records-grc',
            'Template:User records-gsc',
            'Template:User records-guc',
            'Template:User records-guj',
            'Template:User records-ita',
            'Template:User records-jpn',
            'Template:User records-kaj',
            'Template:User records-kcg',
            'Template:User records-ken',
            'Template:User records-kor',
            'Template:User records-kur',
            'Template:User records-lin',
            'Template:User records-mal',
            'Template:User records-mar',
            'Template:User records-min',
            'Template:User records-oci',
            'Template:User records-ori',
            'Template:User records-pan',
            'Template:User records-pol',
            'Template:User records-por',
            'Template:User records-ron',
            'Template:User records-rus',
            'Template:User records-sat',
            'Template:User records-scn',
            'Template:User records-spa',
            'Template:User records-swe',
            'Template:User records-tel',
            'Template:User records-tok',
            'Template:User records-ukr',
            'Template:User records-vie',
            'Template:User records-yue',
            //'Template:Userbox',
            'Template:Userbox-lang',
            'Template:Userbox-records',
            'Template:Userbox-records2',
            //'Template:Userboxbottom',
            //'Template:Userboxtop',
            //'Template:Weak oppose',
            //'Template:Weak support',
            //'Template:White',
            //'Template:Wikt-list',
            //'Template:Worldlex',
            //'Template:Zh other'
        ];

        return inputList
                    // .filter(item => !item.includes('Template:User records'))
                    .filter(item => item !== 'Template:P')
                    .filter(item => item !== 'Template:U')
                    .filter(item => item !== 'Template:T')
                    .filter(item => item !== 'Template:W')
                    .filter(item => item !== 'Template:Userbox')
                    .filter(item => keepList.includes(item));},
    list : [
    "Template:-",
    "Template:100k barnstar",
    "Template:2020 Coolest tool award",
    "Template:50k barnstar",
    "Template:=",
    "Template:Anchor",
    "Template:Audio Error Button",
    "Template:Autopatrolled",
    "Template:Autopatrolled/text",
    "Template:Autopatrolled/text/bn",
    "Template:Autopatrolled/text/de",
    "Template:Autopatrolled/text/en",
    "Template:Autopatrolled/text/fr",
    "Template:Autopatrolled/text/ia",
    "Template:Autopatrolled/text/mk",
    "Template:Autopatrolled/text/oc",
    "Template:Autopatrolled/text/ru",
    "Template:Autopatrolled/text/sv",
    "Template:Autotranslate",
    "Template:BCP47",
    "Template:BUser",
    "Template:Babel field",
    "Template:Babel field N",
    "Template:Black",
    "Template:Bot cycle",
    "Template:Bot steps",
    "Template:Bot steps/Documentation",
    "Template:Bot steps/Documentation/br",
    "Template:Bot steps/Documentation/de",
    "Template:Bot steps/Documentation/en",
    "Template:Bot steps/Documentation/fr",
    "Template:Bot steps/Documentation/mk",
    "Template:Bot steps/Documentation/oc",
    "Template:Bot steps/Documentation/scn",
    "Template:Bot steps/Documentation/sv",
    "Template:Bot steps/text",
    "Template:Bot steps/text/de",
    "Template:Bot steps/text/en",
    "Template:Bot steps/text/fr",
    "Template:Bot steps/text/he",
    "Template:Bot steps/text/mk",
    "Template:Bot steps/text/oc",
    "Template:Bot steps/text/ru",
    "Template:Bot steps/text/sv",
    "Template:CURRENTCONTENTLANGUAGE",
    "Template:Cc-by-sa-4.0",
    "Template:Clear",
    "Template:Clickable button",
    "Template:Clickable button/iconclass",
    "Template:Clickable button 2",
    "Template:Clickable button 2/doc",
    "Template:Clickable button 3",
    "Template:Clr",
    "Template:Col-2",
    "Template:Colapse",
    "Template:Collapse",
    "Template:Collapse/doc",
    "Template:Collapse Templates",
    "Template:Collapse templates",
    "Template:Colon",
    "Template:Color",
    "Template:ColorFrame",
    "Template:Colored box",
    "Template:Colored box/doc",
    "Template:Column-gap",
    "Template:Column-rule",
    "Template:Column-width",
    "Template:DataViz/text",
    "Template:DataViz/text/br",
    "Template:DataViz/text/de",
    "Template:DataViz/text/en",
    "Template:DataViz/text/fr",
    "Template:DataViz/text/he",
    "Template:DataViz/text/id",
    "Template:DataViz/text/ja",
    "Template:DataViz/text/mk",
    "Template:DataViz/text/mnw",
    "Template:DataViz/text/nb",
    "Template:DataViz/text/oc",
    "Template:DataViz/text/sv",
    "Template:Dir",
    "Template:Div col",
    "Template:Div col end",
    "Template:Documentation",
    "Template:Documentation/docspace",
    "Template:Documentation/en",
    "Template:Documentation/end box",
    "Template:Documentation/end box2",
    "Template:Documentation/getText",
    "Template:Documentation/i18n/en",
    "Template:Documentation/layout",
    "Template:Documentation/start box",
    "Template:Documentation/start box2",
    "Template:Documentation/template page",
    "Template:Documentation/text/en",
    "Template:Documentation subpage",
    "Template:Done",
    "Template:Draft",
    "Template:En",
    "Template:Exclusion-list-link",
    "Template:Exclusion list header",
    "Template:Fallback",
    "Template:Flatlist",
    "Template:Flatlist/styles.css",
    "Template:Fmbox",
    "Template:Fr",
    "Template:GT",
    "Template:Gentle ramp",
    "Template:Grants table",
    "Template:Help",
    "Template:Helps",
    "Template:Helps/text",
    "Template:Helps/text/br",
    "Template:Helps/text/de",
    "Template:Helps/text/en",
    "Template:Helps/text/eo",
    "Template:Helps/text/fr",
    "Template:Helps/text/he",
    "Template:Helps/text/mk",
    "Template:Helps/text/mnw",
    "Template:Helps/text/nb",
    "Template:Helps/text/pl",
    "Template:Helps/text/ru",
    "Template:Hermite Dave",
    "Template:High-use",
    "Template:High-use/num",
    "Template:IsDocSubpage",
    "Template:LINGUALEX license",
    "Template:Label",
    "Template:Lang-CR",
    "Template:LangSwitch",
    "Template:LangSwitch/doc",
    "Template:Languageicon",
    "Template:LanguagesGallery",
    "Template:Laugh",
    "Template:LexemeQueriesGenerator",
    "Template:LinguaLex licence",
    "Template:LinguaLibre scripts",
    "Template:Lingua Libre scripts",
    "Template:Ll",
    "Template:Local list license",
    "Template:Localized link",
    "Template:Localized link/en",
    "Template:Lorem ipsum",
    "Template:Lua",
    "Template:Module other",
    "Template:Module rating",
    "Template:Move",
    "Template:Navbox",
    "Template:Notif",
    "Template:Olafbot-exclusion",
    "Template:Olafbot-wikt",
    "Template:Ombox",
    "Template:Ongoing",
    "Template:Oppose",
    "Template:P",
    "Template:PP-template",
    "Template:PR steps",
    "Template:Pagelang",
    "Template:Para",
    "Template:Pause",
    "Template:PedagoWikiCode",
    "Template:PedagoWikiCode/doc",
    "Template:PedagoWikiCode/doc/en",
    "Template:PedagoWikiCode/doc/fr",
    "Template:Ping",
    "Template:Plainlist/styles.css",
    "Template:Pp-meta",
    "Template:Pp-meta/pagetype",
    "Template:Pp-template",
    "Template:Pre2",
    "Template:Projects",
    "Template:Projects/text",
    "Template:Projects/text/br",
    "Template:Projects/text/de",
    "Template:Projects/text/en",
    "Template:Projects/text/eo",
    "Template:Projects/text/fr",
    "Template:Projects/text/he",
    "Template:Projects/text/mk",
    "Template:Projects/text/mnw",
    "Template:Projects/text/nb",
    "Template:Projects/text/pl",
    "Template:Projects/text/pnb",
    "Template:Projects/text/pt-br",
    "Template:Projects/text/ru",
    "Template:Property",
    "Template:Purge",
    "Template:Q",
    "Template:Random number",
    "Template:Random number/doc",
    "Template:Rec",
    "Template:Recommended lists",
    "Template:Record ribbon",
    "Template:Reply to",
    "Template:SOFTREDIRECT",
    "Template:SOTM",
    "Template:SOTY",
    "Template:SUBTLEX-PT",
    "Template:Sandbox other",
    "Template:Shared Template Warning",
    "Template:Shortcut caption/en",
    "Template:Skip",
    "Template:Smile",
    "Template:Soft redirect",
    "Template:Sourire",
    "Template:Sparql2data",
    "Template:Speaker of the month",
    "Template:Speaker of the month/backup",
    "Template:Speaker of the year",
    "Template:Speaker of the year/backup",
    "Template:Speakers category",
    "Template:Str left",
    "Template:Subtlex-ch",
    "Template:Subtlex-cn",
    "Template:Support",
    "Template:SwitchLang",
    "Template:T",
    "Template:T/main",
    "Template:TNT",
    "Template:Technicals",
    "Template:Templ",
    "Template:Templ/doc",
    "Template:TemplateDataHeader",
    "Template:Template other",
    "Template:Template shortcut",
    "Template:Tl",
    "Template:Tlf",
    "Template:Tlp",
    "Template:Tlsp",
    "Template:Tlx",
    "Template:Tmpl",
    "Template:To ISO639-2",
    "Template:To iso 639-2",
    "Template:To iso 639-3",
    "Template:Transclude",
    "Template:Translatable",
    "Template:Translatable/en",
    "Template:Translatable template",
    "Template:Translate",
    "Template:Trim",
    "Template:U",
    "Template:UNILEX license",
    "Template:User SUL Box",
    "Template:User SUL Box/doc",
    "Template:User SUL Box/en",
    "Template:User administrator",
    "Template:User administrator/text",
    "Template:User administrator/text/bn",
    "Template:User administrator/text/br",
    "Template:User administrator/text/de",
    "Template:User administrator/text/fr",
    "Template:User administrator/text/he",
    "Template:User administrator/text/id",
    "Template:User administrator/text/mk",
    "Template:User administrator/text/nb",
    "Template:User administrator/text/oc",
    "Template:User administrator/text/ru",
    "Template:User administrator/text/sv",
    "Template:User administrator/text/yue",
    "Template:User bureaucrat",
    "Template:User bureaucrat/text",
    "Template:User bureaucrat/text/bn",
    "Template:User bureaucrat/text/br",
    "Template:User bureaucrat/text/de",
    "Template:User bureaucrat/text/en",
    "Template:User bureaucrat/text/fr",
    "Template:User bureaucrat/text/he",
    "Template:User bureaucrat/text/id",
    "Template:User bureaucrat/text/mk",
    "Template:User bureaucrat/text/nb",
    "Template:User bureaucrat/text/oc",
    "Template:User bureaucrat/text/ru",
    "Template:User bureaucrat/text/sv",
    "Template:User details",
    "Template:User first 500k",
    "Template:User info",
    "Template:User link",
    "Template:User ratelimit",
    "Template:User records-acy",
    "Template:User records-ami",
    "Template:User records-ara",
    "Template:User records-ban",
    "Template:User records-bcl",
    "Template:User records-bel",
    "Template:User records-ben",
    "Template:User records-bik",
    "Template:User records-blk",
    "Template:User records-cat",
    "Template:User records-cmn",
    "Template:User records-deu",
    "Template:User records-ell",
    "Template:User records-eng",
    "Template:User records-epo",
    "Template:User records-eus",
    "Template:User records-fra",
    "Template:User records-glg",
    "Template:User records-grc",
    "Template:User records-gsc",
    "Template:User records-guc",
    "Template:User records-guj",
    "Template:User records-ita",
    "Template:User records-jpn",
    "Template:User records-kaj",
    "Template:User records-kcg",
    "Template:User records-ken",
    "Template:User records-kor",
    "Template:User records-kur",
    "Template:User records-lin",
    "Template:User records-mal",
    "Template:User records-mar",
    "Template:User records-min",
    "Template:User records-oci",
    "Template:User records-ori",
    "Template:User records-pan",
    "Template:User records-pol",
    "Template:User records-por",
    "Template:User records-ron",
    "Template:User records-rus",
    "Template:User records-sat",
    "Template:User records-scn",
    "Template:User records-spa",
    "Template:User records-swe",
    "Template:User records-tel",
    "Template:User records-tok",
    "Template:User records-ukr",
    "Template:User records-vie",
    "Template:User records-yue",
    "Template:Userbox",
    "Template:Userbox-lang",
    "Template:Userbox-lang/doc",
    "Template:Userbox-records",
    "Template:Userbox-records/doc",
    "Template:Userbox-records/doc/babel",
    "Template:Userbox/doc",
    "Template:Userboxbottom",
    "Template:Userboxtop",
    "Template:W",
    "Template:Weak oppose",
    "Template:Weak support",
    "Template:Welcome",
    "Template:Welcome/doc",
    "Template:Welcome/doc/en",
    "Template:Welcome/doc/fr",
    "Template:Welcome/doc/it",
    "Template:Welcome/lang",
    "Template:Welcome/text",
    "Template:Welcome/text/ban",
    "Template:Welcome/text/bg",
    "Template:Welcome/text/bn",
    "Template:Welcome/text/br",
    "Template:Welcome/text/ca",
    "Template:Welcome/text/de",
    "Template:Welcome/text/en",
    "Template:Welcome/text/eo",
    "Template:Welcome/text/fi",
    "Template:Welcome/text/fr",
    "Template:Welcome/text/gl",
    "Template:Welcome/text/he",
    "Template:Welcome/text/id",
    "Template:Welcome/text/ja",
    "Template:Welcome/text/lt",
    "Template:Welcome/text/mk",
    "Template:Welcome/text/mnw",
    "Template:Welcome/text/ms",
    "Template:Welcome/text/nb",
    "Template:Welcome/text/oc",
    "Template:Welcome/text/pl",
    "Template:Welcome/text/ru",
    "Template:Welcome/text/scn",
    "Template:Welcome/text/sv",
    "Template:Welcome/text/ta",
    "Template:Welcome/text/te",
    "Template:Welcome/text/uk",
    "Template:White",
    "Template:Wikt-list",
    "Template:Worldlex",
    "Template:Zh other"
]
};

// Export to global scope for browser access
if (typeof window !== 'undefined') {
    window.template = template;
}